//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LoginMsg.proto
namespace GameP
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SLogin")]
  public partial class C2SLogin : global::ProtoBuf.IExtensible
  {
    public C2SLogin() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private int _clientType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"clientType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int clientType
    {
      get { return _clientType; }
      set { _clientType = value; }
    }
    private int _channelId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"channelId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int channelId
    {
      get { return _channelId; }
      set { _channelId = value; }
    }
    private int _loginType;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"loginType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int loginType
    {
      get { return _loginType; }
      set { _loginType = value; }
    }
    private string _deviceType;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"deviceType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string deviceType
    {
      get { return _deviceType; }
      set { _deviceType = value; }
    }
    private string _deviceId;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"deviceId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string deviceId
    {
      get { return _deviceId; }
      set { _deviceId = value; }
    }
    private string _parameters = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"parameters", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string parameters
    {
      get { return _parameters; }
      set { _parameters = value; }
    }
    private string _nickName = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private string _versionNo = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"versionNo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string versionNo
    {
      get { return _versionNo; }
      set { _versionNo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CLogin")]
  public partial class S2CLogin : global::ProtoBuf.IExtensible
  {
    public S2CLogin() {}
    
    private ulong _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private AreaInfo _areaInfo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"areaInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public AreaInfo areaInfo
    {
      get { return _areaInfo; }
      set { _areaInfo = value; }
    }
    private int _isFirstLogin = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"isFirstLogin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int isFirstLogin
    {
      get { return _isFirstLogin; }
      set { _isFirstLogin = value; }
    }
    private int _channelId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"channelId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int channelId
    {
      get { return _channelId; }
      set { _channelId = value; }
    }
    private string _sessionId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"sessionId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sessionId
    {
      get { return _sessionId; }
      set { _sessionId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AreaInfo")]
  public partial class AreaInfo : global::ProtoBuf.IExtensible
  {
    public AreaInfo() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _areaIp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"areaIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string areaIp
    {
      get { return _areaIp; }
      set { _areaIp = value; }
    }
    private int _areaPort;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"areaPort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int areaPort
    {
      get { return _areaPort; }
      set { _areaPort = value; }
    }
    private int _status;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}