//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ActivationMsg.proto
namespace ActivationMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SActivationReceive")]
  public partial class C2SActivationReceive : global::ProtoBuf.IExtensible
  {
    public C2SActivationReceive() {}
    
    private int _channelId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"channelId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int channelId
    {
      get { return _channelId; }
      set { _channelId = value; }
    }
    private string _activationCode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"activationCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string activationCode
    {
      get { return _activationCode; }
      set { _activationCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CActivationReceive")]
  public partial class S2CActivationReceive : global::ProtoBuf.IExtensible
  {
    public S2CActivationReceive() {}
    
    private int _activationStatus = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"activationStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int activationStatus
    {
      get { return _activationStatus; }
      set { _activationStatus = value; }
    }
    private string _rewardsContent = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rewardsContent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string rewardsContent
    {
      get { return _rewardsContent; }
      set { _rewardsContent = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}