//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: camera_control.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CAMERA_CONTROL")]
  public partial class CAMERA_CONTROL : global::ProtoBuf.IExtensible
  {
    public CAMERA_CONTROL() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private float _target_z;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"target_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float target_z
    {
      get { return _target_z; }
      set { _target_z = value; }
    }
    private float _speed = (float)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private float _stay_time = (float)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"stay_time", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float stay_time
    {
      get { return _stay_time; }
      set { _stay_time = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CAMERA_CONTROL_ARRAY")]
  public partial class CAMERA_CONTROL_ARRAY : global::ProtoBuf.IExtensible
  {
    public CAMERA_CONTROL_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.CAMERA_CONTROL> _items = new global::System.Collections.Generic.List<deploy.CAMERA_CONTROL>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.CAMERA_CONTROL> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}