//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: chapter.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CHAPTER")]
  public partial class CHAPTER : global::ProtoBuf.IExtensible
  {
    public CHAPTER() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _order = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"order", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int order
    {
      get { return _order; }
      set { _order = value; }
    }
    private int _nextChapter = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"nextChapter", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int nextChapter
    {
      get { return _nextChapter; }
      set { _nextChapter = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _nameIcon = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"nameIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nameIcon
    {
      get { return _nameIcon; }
      set { _nameIcon = value; }
    }
    private string _background = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"background", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string background
    {
      get { return _background; }
      set { _background = value; }
    }
    private string _terrainimage = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"terrainimage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string terrainimage
    {
      get { return _terrainimage; }
      set { _terrainimage = value; }
    }
    private string _position = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string position
    {
      get { return _position; }
      set { _position = value; }
    }
    private int _chapter = (int)0;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"chapter", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int chapter
    {
      get { return _chapter; }
      set { _chapter = value; }
    }
    private int _xingxing = (int)0;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"xingxing", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int xingxing
    {
      get { return _xingxing; }
      set { _xingxing = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CHAPTER_ARRAY")]
  public partial class CHAPTER_ARRAY : global::ProtoBuf.IExtensible
  {
    public CHAPTER_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.CHAPTER> _items = new global::System.Collections.Generic.List<deploy.CHAPTER>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.CHAPTER> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}