//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: chapter_star_award.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CHAPTER_STAR_AWARD")]
  public partial class CHAPTER_STAR_AWARD : global::ProtoBuf.IExtensible
  {
    public CHAPTER_STAR_AWARD() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _starnum = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"starnum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int starnum
    {
      get { return _starnum; }
      set { _starnum = value; }
    }
    private string _bonusitem = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"bonusitem", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bonusitem
    {
      get { return _bonusitem; }
      set { _bonusitem = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CHAPTER_STAR_AWARD_ARRAY")]
  public partial class CHAPTER_STAR_AWARD_ARRAY : global::ProtoBuf.IExtensible
  {
    public CHAPTER_STAR_AWARD_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.CHAPTER_STAR_AWARD> _items = new global::System.Collections.Generic.List<deploy.CHAPTER_STAR_AWARD>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.CHAPTER_STAR_AWARD> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}