//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: chess_multiple.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CHESS_MULTIPLE")]
  public partial class CHESS_MULTIPLE : global::ProtoBuf.IExtensible
  {
    public CHESS_MULTIPLE() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private float _eliminate_multiple = (float)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"eliminate_multiple", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float eliminate_multiple
    {
      get { return _eliminate_multiple; }
      set { _eliminate_multiple = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CHESS_MULTIPLE_ARRAY")]
  public partial class CHESS_MULTIPLE_ARRAY : global::ProtoBuf.IExtensible
  {
    public CHESS_MULTIPLE_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.CHESS_MULTIPLE> _items = new global::System.Collections.Generic.List<deploy.CHESS_MULTIPLE>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.CHESS_MULTIPLE> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}