//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: chessbuff.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CHESSBUFF")]
  public partial class CHESSBUFF : global::ProtoBuf.IExtensible
  {
    public CHESSBUFF() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _skill_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"skill_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skill_id
    {
      get { return _skill_id; }
      set { _skill_id = value; }
    }
    private int _type = (int)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _round = (int)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"round", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int round
    {
      get { return _round; }
      set { _round = value; }
    }
    private int _life = (int)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"life", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int life
    {
      get { return _life; }
      set { _life = value; }
    }
    private int _amount = (int)0;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int amount
    {
      get { return _amount; }
      set { _amount = value; }
    }
    private int _intensify_num = (int)0;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"intensify_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int intensify_num
    {
      get { return _intensify_num; }
      set { _intensify_num = value; }
    }
    private int _purify_chess = (int)0;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"purify_chess", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int purify_chess
    {
      get { return _purify_chess; }
      set { _purify_chess = value; }
    }
    private string _branch_type = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"branch_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string branch_type
    {
      get { return _branch_type; }
      set { _branch_type = value; }
    }
    private int _branch_round = (int)0;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"branch_round", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int branch_round
    {
      get { return _branch_round; }
      set { _branch_round = value; }
    }
    private int _branch_amount = (int)0;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"branch_amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int branch_amount
    {
      get { return _branch_amount; }
      set { _branch_amount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CHESSBUFF_ARRAY")]
  public partial class CHESSBUFF_ARRAY : global::ProtoBuf.IExtensible
  {
    public CHESSBUFF_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.CHESSBUFF> _items = new global::System.Collections.Generic.List<deploy.CHESSBUFF>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.CHESSBUFF> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}