//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: chess_base_score.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CHESS_BASE_SCORE")]
  public partial class CHESS_BASE_SCORE : global::ProtoBuf.IExtensible
  {
    public CHESS_BASE_SCORE() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _eliminate_score = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"eliminate_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int eliminate_score
    {
      get { return _eliminate_score; }
      set { _eliminate_score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CHESS_BASE_SCORE_ARRAY")]
  public partial class CHESS_BASE_SCORE_ARRAY : global::ProtoBuf.IExtensible
  {
    public CHESS_BASE_SCORE_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.CHESS_BASE_SCORE> _items = new global::System.Collections.Generic.List<deploy.CHESS_BASE_SCORE>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.CHESS_BASE_SCORE> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}