//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: damage.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DAMAGE")]
  public partial class DAMAGE : global::ProtoBuf.IExtensible
  {
    public DAMAGE() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _order;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"order", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int order
    {
      get { return _order; }
      set { _order = value; }
    }
    private int _hero_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"hero_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hero_id
    {
      get { return _hero_id; }
      set { _hero_id = value; }
    }
    private int _open_condition;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"open_condition", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int open_condition
    {
      get { return _open_condition; }
      set { _open_condition = value; }
    }
    private int _skill_typeone;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"skill_typeone", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skill_typeone
    {
      get { return _skill_typeone; }
      set { _skill_typeone = value; }
    }
    private int _open_value;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"open_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int open_value
    {
      get { return _open_value; }
      set { _open_value = value; }
    }
    private string _icon_resource = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"icon_resource", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon_resource
    {
      get { return _icon_resource; }
      set { _icon_resource = value; }
    }
    private int _icon_resid = (int)0;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"icon_resid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int icon_resid
    {
      get { return _icon_resid; }
      set { _icon_resid = value; }
    }
    private string _icon_pvp = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"icon_pvp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon_pvp
    {
      get { return _icon_pvp; }
      set { _icon_pvp = value; }
    }
    private int _desc = (int)0;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private int _initial_level = (int)0;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"initial_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int initial_level
    {
      get { return _initial_level; }
      set { _initial_level = value; }
    }
    private int _level_max = (int)0;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"level_max", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int level_max
    {
      get { return _level_max; }
      set { _level_max = value; }
    }
    private int _skill_coefficient = (int)0;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"skill_coefficient", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int skill_coefficient
    {
      get { return _skill_coefficient; }
      set { _skill_coefficient = value; }
    }
    private int _coefficient_growth = (int)0;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"coefficient_growth", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int coefficient_growth
    {
      get { return _coefficient_growth; }
      set { _coefficient_growth = value; }
    }
    private float _base_value = (float)0;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"base_value", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float base_value
    {
      get { return _base_value; }
      set { _base_value = value; }
    }
    private float _numerical_growth = (float)0;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"numerical_growth", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float numerical_growth
    {
      get { return _numerical_growth; }
      set { _numerical_growth = value; }
    }
    private int _change_heroattr = (int)0;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"change_heroattr", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int change_heroattr
    {
      get { return _change_heroattr; }
      set { _change_heroattr = value; }
    }
    private int _combatattr_id = (int)0;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"combatattr_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int combatattr_id
    {
      get { return _combatattr_id; }
      set { _combatattr_id = value; }
    }
    private int _skill_type = (int)0;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"skill_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int skill_type
    {
      get { return _skill_type; }
      set { _skill_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DAMAGE_ARRAY")]
  public partial class DAMAGE_ARRAY : global::ProtoBuf.IExtensible
  {
    public DAMAGE_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.DAMAGE> _items = new global::System.Collections.Generic.List<deploy.DAMAGE>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.DAMAGE> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}