//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: dialog_config.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DIALOG_CONFIG")]
  public partial class DIALOG_CONFIG : global::ProtoBuf.IExtensible
  {
    public DIALOG_CONFIG() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _triggerAlign = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"triggerAlign", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int triggerAlign
    {
      get { return _triggerAlign; }
      set { _triggerAlign = value; }
    }
    private int _headID = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"headID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int headID
    {
      get { return _headID; }
      set { _headID = value; }
    }
    private string _soundEffect = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"soundEffect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string soundEffect
    {
      get { return _soundEffect; }
      set { _soundEffect = value; }
    }
    private string _localizationKey = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"localizationKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string localizationKey
    {
      get { return _localizationKey; }
      set { _localizationKey = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DIALOG_CONFIG_ARRAY")]
  public partial class DIALOG_CONFIG_ARRAY : global::ProtoBuf.IExtensible
  {
    public DIALOG_CONFIG_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.DIALOG_CONFIG> _items = new global::System.Collections.Generic.List<deploy.DIALOG_CONFIG>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.DIALOG_CONFIG> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}