//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: fighting.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FIGHTING")]
  public partial class FIGHTING : global::ProtoBuf.IExtensible
  {
    public FIGHTING() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _attribute_type = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"attribute_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string attribute_type
    {
      get { return _attribute_type; }
      set { _attribute_type = value; }
    }
    private float _utility_coefficient = (float)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"utility_coefficient", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float utility_coefficient
    {
      get { return _utility_coefficient; }
      set { _utility_coefficient = value; }
    }
    private float _force_coefficient = (float)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"force_coefficient", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float force_coefficient
    {
      get { return _force_coefficient; }
      set { _force_coefficient = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FIGHTING_ARRAY")]
  public partial class FIGHTING_ARRAY : global::ProtoBuf.IExtensible
  {
    public FIGHTING_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.FIGHTING> _items = new global::System.Collections.Generic.List<deploy.FIGHTING>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.FIGHTING> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}