//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: FightMsg.proto
// Note: requires additional types generated from: GuildMsg.proto
using GuildMsg;
namespace FightMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SFightHeartbeat")]
  public partial class C2SFightHeartbeat : global::ProtoBuf.IExtensible
  {
    public C2SFightHeartbeat() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CFightHeartbeat")]
  public partial class S2CFightHeartbeat : global::ProtoBuf.IExtensible
  {
    public S2CFightHeartbeat() {}
    
    private long _nowTime = (long)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"nowTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)0)]
    public long nowTime
    {
      get { return _nowTime; }
      set { _nowTime = value; }
    }
    private int _timeZone = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"timeZone", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int timeZone
    {
      get { return _timeZone; }
      set { _timeZone = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SFightEnterRoom")]
  public partial class C2SFightEnterRoom : global::ProtoBuf.IExtensible
  {
    public C2SFightEnterRoom() {}
    
    private long _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private long _playerId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _token;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private int _isReEnter;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"isReEnter", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int isReEnter
    {
      get { return _isReEnter; }
      set { _isReEnter = value; }
    }
    private string _versionNo = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"versionNo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string versionNo
    {
      get { return _versionNo; }
      set { _versionNo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CFightEnterRoom")]
  public partial class S2CFightEnterRoom : global::ProtoBuf.IExtensible
  {
    public S2CFightEnterRoom() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CFightPVpStart")]
  public partial class S2CFightPVpStart : global::ProtoBuf.IExtensible
  {
    public S2CFightPVpStart() {}
    
    private FightRoundInfo _roundInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roundInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public FightRoundInfo roundInfo
    {
      get { return _roundInfo; }
      set { _roundInfo = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _randomSeed = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"randomSeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> randomSeed
    {
      get { return _randomSeed; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SFightSelectHero")]
  public partial class C2SFightSelectHero : global::ProtoBuf.IExtensible
  {
    public C2SFightSelectHero() {}
    
    private readonly global::System.Collections.Generic.List<int> _selectHeros = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"selectHeros", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> selectHeros
    {
      get { return _selectHeros; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CFigthSelectHero")]
  public partial class S2CFigthSelectHero : global::ProtoBuf.IExtensible
  {
    public S2CFigthSelectHero() {}
    
    private FightRoundInfo _roundInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roundInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public FightRoundInfo roundInfo
    {
      get { return _roundInfo; }
      set { _roundInfo = value; }
    }
    private readonly global::System.Collections.Generic.List<HeroInfo> _selfHeros = new global::System.Collections.Generic.List<HeroInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"selfHeros", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<HeroInfo> selfHeros
    {
      get { return _selfHeros; }
    }
  
    private readonly global::System.Collections.Generic.List<HeroInfo> _enemyHeros = new global::System.Collections.Generic.List<HeroInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"enemyHeros", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<HeroInfo> enemyHeros
    {
      get { return _enemyHeros; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SFightAjdustCamp")]
  public partial class C2SFightAjdustCamp : global::ProtoBuf.IExtensible
  {
    public C2SFightAjdustCamp() {}
    
    private readonly global::System.Collections.Generic.List<int> _herosIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"herosIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> herosIds
    {
      get { return _herosIds; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CFightAdjustCamp")]
  public partial class S2CFightAdjustCamp : global::ProtoBuf.IExtensible
  {
    public S2CFightAdjustCamp() {}
    
    private FightRoundInfo _roundInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roundInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FightRoundInfo roundInfo
    {
      get { return _roundInfo; }
      set { _roundInfo = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _selfCamp = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"selfCamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> selfCamp
    {
      get { return _selfCamp; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _enemyCamp = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"enemyCamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> enemyCamp
    {
      get { return _enemyCamp; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SFightMsgInfo")]
  public partial class C2SFightMsgInfo : global::ProtoBuf.IExtensible
  {
    public C2SFightMsgInfo() {}
    
    private readonly global::System.Collections.Generic.List<FightMsgInfo> _fightMsgInfo = new global::System.Collections.Generic.List<FightMsgInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"fightMsgInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FightMsgInfo> fightMsgInfo
    {
      get { return _fightMsgInfo; }
    }
  
    private readonly global::System.Collections.Generic.List<FightHeroInfo> _fightHeroList = new global::System.Collections.Generic.List<FightHeroInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"fightHeroList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FightHeroInfo> fightHeroList
    {
      get { return _fightHeroList; }
    }
  
    private int _attackFlag = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"attackFlag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int attackFlag
    {
      get { return _attackFlag; }
      set { _attackFlag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CFightMsgInfo")]
  public partial class S2CFightMsgInfo : global::ProtoBuf.IExtensible
  {
    public S2CFightMsgInfo() {}
    
    private readonly global::System.Collections.Generic.List<FightMsgInfo> _fightMsgInfo = new global::System.Collections.Generic.List<FightMsgInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"fightMsgInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FightMsgInfo> fightMsgInfo
    {
      get { return _fightMsgInfo; }
    }
  
    private readonly global::System.Collections.Generic.List<FightHeroInfo> _fightHeroList = new global::System.Collections.Generic.List<FightHeroInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"fightHeroList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FightHeroInfo> fightHeroList
    {
      get { return _fightHeroList; }
    }
  
    private int _attackFlag = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"attackFlag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int attackFlag
    {
      get { return _attackFlag; }
      set { _attackFlag = value; }
    }
    private FightRoundInfo _roundInfo = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"roundInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FightRoundInfo roundInfo
    {
      get { return _roundInfo; }
      set { _roundInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SChessBuffInfo")]
  public partial class C2SChessBuffInfo : global::ProtoBuf.IExtensible
  {
    public C2SChessBuffInfo() {}
    
    private readonly global::System.Collections.Generic.List<ChessBuffInfo> _chessBuffList = new global::System.Collections.Generic.List<ChessBuffInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"chessBuffList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ChessBuffInfo> chessBuffList
    {
      get { return _chessBuffList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CChessBuffInfo")]
  public partial class S2CChessBuffInfo : global::ProtoBuf.IExtensible
  {
    public S2CChessBuffInfo() {}
    
    private readonly global::System.Collections.Generic.List<ChessBuffInfo> _chessBuffList = new global::System.Collections.Generic.List<ChessBuffInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"chessBuffList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ChessBuffInfo> chessBuffList
    {
      get { return _chessBuffList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SFightLoadRes")]
  public partial class C2SFightLoadRes : global::ProtoBuf.IExtensible
  {
    public C2SFightLoadRes() {}
    
    private float _progress = (float)1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"progress", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)1)]
    public float progress
    {
      get { return _progress; }
      set { _progress = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CFightLoadRes")]
  public partial class S2CFightLoadRes : global::ProtoBuf.IExtensible
  {
    public S2CFightLoadRes() {}
    
    private FightRoundInfo _roundInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roundInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public FightRoundInfo roundInfo
    {
      get { return _roundInfo; }
      set { _roundInfo = value; }
    }
    private long _completeId = (long)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"completeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)0)]
    public long completeId
    {
      get { return _completeId; }
      set { _completeId = value; }
    }
    private float _progress = (float)1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"progress", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)1)]
    public float progress
    {
      get { return _progress; }
      set { _progress = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CRoomStateChange")]
  public partial class S2CRoomStateChange : global::ProtoBuf.IExtensible
  {
    public S2CRoomStateChange() {}
    
    private FightRoundInfo _roundInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roundInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public FightRoundInfo roundInfo
    {
      get { return _roundInfo; }
      set { _roundInfo = value; }
    }
    private long _changePlayer = (long)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"changePlayer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)0)]
    public long changePlayer
    {
      get { return _changePlayer; }
      set { _changePlayer = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SFightFace")]
  public partial class C2SFightFace : global::ProtoBuf.IExtensible
  {
    public C2SFightFace() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CFightFace")]
  public partial class S2CFightFace : global::ProtoBuf.IExtensible
  {
    public S2CFightFace() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SFightChessDead")]
  public partial class C2SFightChessDead : global::ProtoBuf.IExtensible
  {
    public C2SFightChessDead() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CFightChessDead")]
  public partial class S2CFightChessDead : global::ProtoBuf.IExtensible
  {
    public S2CFightChessDead() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FightRoundInfo")]
  public partial class FightRoundInfo : global::ProtoBuf.IExtensible
  {
    public FightRoundInfo() {}
    
    private int _phase;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"phase", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int phase
    {
      get { return _phase; }
      set { _phase = value; }
    }
    private long _timeout;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"timeout", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long timeout
    {
      get { return _timeout; }
      set { _timeout = value; }
    }
    private long _turnId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"turnId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long turnId
    {
      get { return _turnId; }
      set { _turnId = value; }
    }
    private int _roundCount;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"roundCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roundCount
    {
      get { return _roundCount; }
      set { _roundCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FightMsgInfo")]
  public partial class FightMsgInfo : global::ProtoBuf.IExtensible
  {
    public FightMsgInfo() {}
    
    private int _msgId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int msgId
    {
      get { return _msgId; }
      set { _msgId = value; }
    }
    private int _skillId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillId
    {
      get { return _skillId; }
      set { _skillId = value; }
    }
    private int _skillLv;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"skillLv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillLv
    {
      get { return _skillLv; }
      set { _skillLv = value; }
    }
    private int _attackerIndex;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"attackerIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attackerIndex
    {
      get { return _attackerIndex; }
      set { _attackerIndex = value; }
    }
    private int _attackerType;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"attackerType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attackerType
    {
      get { return _attackerType; }
      set { _attackerType = value; }
    }
    private int _randomIndex;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"randomIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int randomIndex
    {
      get { return _randomIndex; }
      set { _randomIndex = value; }
    }
    private int _skillType = (int)-1;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"skillType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int skillType
    {
      get { return _skillType; }
      set { _skillType = value; }
    }
    private int _computeType = (int)0;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"computeType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int computeType
    {
      get { return _computeType; }
      set { _computeType = value; }
    }
    private int _comboType = (int)0;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"comboType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int comboType
    {
      get { return _comboType; }
      set { _comboType = value; }
    }
    private float _comboCount = (float)1;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"comboCount", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)1)]
    public float comboCount
    {
      get { return _comboCount; }
      set { _comboCount = value; }
    }
    private int _normalExtra = (int)0;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"normalExtra", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int normalExtra
    {
      get { return _normalExtra; }
      set { _normalExtra = value; }
    }
    private int _fourExtra = (int)0;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"fourExtra", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int fourExtra
    {
      get { return _fourExtra; }
      set { _fourExtra = value; }
    }
    private int _tlExtraCount = (int)0;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"tlExtraCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int tlExtraCount
    {
      get { return _tlExtraCount; }
      set { _tlExtraCount = value; }
    }
    private int _playFlag = (int)0;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"playFlag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int playFlag
    {
      get { return _playFlag; }
      set { _playFlag = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _randomList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(15, Name=@"randomList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> randomList
    {
      get { return _randomList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FightHeroInfo")]
  public partial class FightHeroInfo : global::ProtoBuf.IExtensible
  {
    public FightHeroInfo() {}
    
    private int _msgId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int msgId
    {
      get { return _msgId; }
      set { _msgId = value; }
    }
    private int _index;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _isEnemy;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"isEnemy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int isEnemy
    {
      get { return _isEnemy; }
      set { _isEnemy = value; }
    }
    private int _infoType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"infoType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int infoType
    {
      get { return _infoType; }
      set { _infoType = value; }
    }
    private float _hp = default(float);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _damageValue = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"damageValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int damageValue
    {
      get { return _damageValue; }
      set { _damageValue = value; }
    }
    private int _hitId = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"hitId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hitId
    {
      get { return _hitId; }
      set { _hitId = value; }
    }
    private int _critId = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"critId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int critId
    {
      get { return _critId; }
      set { _critId = value; }
    }
    private int _flagParam = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"flagParam", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int flagParam
    {
      get { return _flagParam; }
      set { _flagParam = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChessBuffInfo")]
  public partial class ChessBuffInfo : global::ProtoBuf.IExtensible
  {
    public ChessBuffInfo() {}
    
    private int _chessType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"chessType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int chessType
    {
      get { return _chessType; }
      set { _chessType = value; }
    }
    private int _num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}