//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: formation.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FORMATION")]
  public partial class FORMATION : global::ProtoBuf.IExtensible
  {
    public FORMATION() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private string _desc = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private int _count = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private string _first = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"first", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string first
    {
      get { return _first; }
      set { _first = value; }
    }
    private string _second = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"second", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string second
    {
      get { return _second; }
      set { _second = value; }
    }
    private string _third = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"third", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string third
    {
      get { return _third; }
      set { _third = value; }
    }
    private string _fourth = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"fourth", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fourth
    {
      get { return _fourth; }
      set { _fourth = value; }
    }
    private string _fifth = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"fifth", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fifth
    {
      get { return _fifth; }
      set { _fifth = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FORMATION_ARRAY")]
  public partial class FORMATION_ARRAY : global::ProtoBuf.IExtensible
  {
    public FORMATION_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.FORMATION> _items = new global::System.Collections.Generic.List<deploy.FORMATION>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.FORMATION> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}