//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: FriendMsg.proto
namespace FriendMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SFriendInfoList")]
  public partial class C2SFriendInfoList : global::ProtoBuf.IExtensible
  {
    public C2SFriendInfoList() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CFriendInfoList")]
  public partial class S2CFriendInfoList : global::ProtoBuf.IExtensible
  {
    public S2CFriendInfoList() {}
    
    private readonly global::System.Collections.Generic.List<FriendInfo> _friends = new global::System.Collections.Generic.List<FriendInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"friends", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FriendInfo> friends
    {
      get { return _friends; }
    }
  
    private int _ret;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SFriendApplyList")]
  public partial class C2SFriendApplyList : global::ProtoBuf.IExtensible
  {
    public C2SFriendApplyList() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CFriendApplyList")]
  public partial class S2CFriendApplyList : global::ProtoBuf.IExtensible
  {
    public S2CFriendApplyList() {}
    
    private readonly global::System.Collections.Generic.List<FriendInfo> _friends = new global::System.Collections.Generic.List<FriendInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"friends", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FriendInfo> friends
    {
      get { return _friends; }
    }
  
    private int _ret;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SFriendLookList")]
  public partial class C2SFriendLookList : global::ProtoBuf.IExtensible
  {
    public C2SFriendLookList() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CFriendLookList")]
  public partial class S2CFriendLookList : global::ProtoBuf.IExtensible
  {
    public S2CFriendLookList() {}
    
    private readonly global::System.Collections.Generic.List<FriendInfo> _friends = new global::System.Collections.Generic.List<FriendInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"friends", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FriendInfo> friends
    {
      get { return _friends; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _coolTime = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(3, Name=@"coolTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> coolTime
    {
      get { return _coolTime; }
    }
  
    private int _ret;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SFriendAddApply")]
  public partial class C2SFriendAddApply : global::ProtoBuf.IExtensible
  {
    public C2SFriendAddApply() {}
    
    private readonly global::System.Collections.Generic.List<long> _friendId = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(2, Name=@"friendId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> friendId
    {
      get { return _friendId; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CFriendAddApply")]
  public partial class S2CFriendAddApply : global::ProtoBuf.IExtensible
  {
    public S2CFriendAddApply() {}
    
    private readonly global::System.Collections.Generic.List<long> _friendId = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(1, Name=@"friendId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> friendId
    {
      get { return _friendId; }
    }
  
    private int _ret;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SFriendAddAgree")]
  public partial class C2SFriendAddAgree : global::ProtoBuf.IExtensible
  {
    public C2SFriendAddAgree() {}
    
    private readonly global::System.Collections.Generic.List<long> _friendId = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(2, Name=@"friendId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> friendId
    {
      get { return _friendId; }
    }
  
    private int _add;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"add", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int add
    {
      get { return _add; }
      set { _add = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CFriendAddAgree")]
  public partial class S2CFriendAddAgree : global::ProtoBuf.IExtensible
  {
    public S2CFriendAddAgree() {}
    
    private readonly global::System.Collections.Generic.List<long> _friendId = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(1, Name=@"friendId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> friendId
    {
      get { return _friendId; }
    }
  
    private int _add;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"add", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int add
    {
      get { return _add; }
      set { _add = value; }
    }
    private int _ret;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SFriendRelationDel")]
  public partial class C2SFriendRelationDel : global::ProtoBuf.IExtensible
  {
    public C2SFriendRelationDel() {}
    
    private readonly global::System.Collections.Generic.List<long> _friendIds = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(1, Name=@"friendIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> friendIds
    {
      get { return _friendIds; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CFriendRelationDel")]
  public partial class S2CFriendRelationDel : global::ProtoBuf.IExtensible
  {
    public S2CFriendRelationDel() {}
    
    private readonly global::System.Collections.Generic.List<long> _friendIds = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(1, Name=@"friendIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> friendIds
    {
      get { return _friendIds; }
    }
  
    private int _ret;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SFriendStrengthGift")]
  public partial class C2SFriendStrengthGift : global::ProtoBuf.IExtensible
  {
    public C2SFriendStrengthGift() {}
    
    private readonly global::System.Collections.Generic.List<long> _strengthId = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(1, Name=@"strengthId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> strengthId
    {
      get { return _strengthId; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SFriendStrengthGet")]
  public partial class C2SFriendStrengthGet : global::ProtoBuf.IExtensible
  {
    public C2SFriendStrengthGet() {}
    
    private readonly global::System.Collections.Generic.List<long> _strengthId = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(1, Name=@"strengthId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> strengthId
    {
      get { return _strengthId; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SFriendSearch")]
  public partial class C2SFriendSearch : global::ProtoBuf.IExtensible
  {
    public C2SFriendSearch() {}
    
    private long _friendId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"friendId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long friendId
    {
      get { return _friendId; }
      set { _friendId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CFriendSearch")]
  public partial class S2CFriendSearch : global::ProtoBuf.IExtensible
  {
    public S2CFriendSearch() {}
    
    private int _ret;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private FriendInfo _friendInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"friendInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FriendInfo friendInfo
    {
      get { return _friendInfo; }
      set { _friendInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SFriendAskforStrength")]
  public partial class C2SFriendAskforStrength : global::ProtoBuf.IExtensible
  {
    public C2SFriendAskforStrength() {}
    
    private readonly global::System.Collections.Generic.List<long> _friendId = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(1, Name=@"friendId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> friendId
    {
      get { return _friendId; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CFriendAskforStrength")]
  public partial class S2CFriendAskforStrength : global::ProtoBuf.IExtensible
  {
    public S2CFriendAskforStrength() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _askDaily;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"askDaily", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int askDaily
    {
      get { return _askDaily; }
      set { _askDaily = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SFriendAskforManager")]
  public partial class C2SFriendAskforManager : global::ProtoBuf.IExtensible
  {
    public C2SFriendAskforManager() {}
    
    private int _option;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"option", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int option
    {
      get { return _option; }
      set { _option = value; }
    }
    private readonly global::System.Collections.Generic.List<StrengthManagerInfo> _friends = new global::System.Collections.Generic.List<StrengthManagerInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"friends", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<StrengthManagerInfo> friends
    {
      get { return _friends; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CFriendAskforManager")]
  public partial class S2CFriendAskforManager : global::ProtoBuf.IExtensible
  {
    public S2CFriendAskforManager() {}
    
    private readonly global::System.Collections.Generic.List<FriendInfo> _friends = new global::System.Collections.Generic.List<FriendInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"friends", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FriendInfo> friends
    {
      get { return _friends; }
    }
  
    private int _gainDaily;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"gainDaily", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gainDaily
    {
      get { return _gainDaily; }
      set { _gainDaily = value; }
    }
    private int _giveDaily;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"giveDaily", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int giveDaily
    {
      get { return _giveDaily; }
      set { _giveDaily = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SOverstepFriendShow")]
  public partial class C2SOverstepFriendShow : global::ProtoBuf.IExtensible
  {
    public C2SOverstepFriendShow() {}
    
    private int _showType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"showType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int showType
    {
      get { return _showType; }
      set { _showType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2COverstepFriendShow")]
  public partial class S2COverstepFriendShow : global::ProtoBuf.IExtensible
  {
    public S2COverstepFriendShow() {}
    
    private int _showType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"showType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int showType
    {
      get { return _showType; }
      set { _showType = value; }
    }
    private int _dailyNum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"dailyNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dailyNum
    {
      get { return _dailyNum; }
      set { _dailyNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SPlatformFriendsSync")]
  public partial class C2SPlatformFriendsSync : global::ProtoBuf.IExtensible
  {
    public C2SPlatformFriendsSync() {}
    
    private readonly global::System.Collections.Generic.List<FriendPlafrom> _friends = new global::System.Collections.Generic.List<FriendPlafrom>();
    [global::ProtoBuf.ProtoMember(1, Name=@"friends", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FriendPlafrom> friends
    {
      get { return _friends; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CPlatformFriendsSync")]
  public partial class S2CPlatformFriendsSync : global::ProtoBuf.IExtensible
  {
    public S2CPlatformFriendsSync() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendInfo")]
  public partial class FriendInfo : global::ProtoBuf.IExtensible
  {
    public FriendInfo() {}
    
    private long _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private int _loginType = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"loginType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int loginType
    {
      get { return _loginType; }
      set { _loginType = value; }
    }
    private int _playerLevel = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"playerLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int playerLevel
    {
      get { return _playerLevel; }
      set { _playerLevel = value; }
    }
    private string _icon = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private string _playerName = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"playerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playerName
    {
      get { return _playerName; }
      set { _playerName = value; }
    }
    private int _unionId = (int)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"unionId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int unionId
    {
      get { return _unionId; }
      set { _unionId = value; }
    }
    private string _unionName = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"unionName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string unionName
    {
      get { return _unionName; }
      set { _unionName = value; }
    }
    private int _logoBg = (int)0;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"logoBg", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int logoBg
    {
      get { return _logoBg; }
      set { _logoBg = value; }
    }
    private int _logoStyele = (int)0;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"logoStyele", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int logoStyele
    {
      get { return _logoStyele; }
      set { _logoStyele = value; }
    }
    private int _logoBorder = (int)0;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"logoBorder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int logoBorder
    {
      get { return _logoBorder; }
      set { _logoBorder = value; }
    }
    private long _offlineTime = (long)0;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"offlineTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)0)]
    public long offlineTime
    {
      get { return _offlineTime; }
      set { _offlineTime = value; }
    }
    private int _isOnline = (int)0;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"isOnline", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int isOnline
    {
      get { return _isOnline; }
      set { _isOnline = value; }
    }
    private int _iconType = (int)0;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"iconType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int iconType
    {
      get { return _iconType; }
      set { _iconType = value; }
    }
    private int _pvpOlScore = (int)0;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"pvpOlScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int pvpOlScore
    {
      get { return _pvpOlScore; }
      set { _pvpOlScore = value; }
    }
    private int _canAskfor = (int)0;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"canAskfor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int canAskfor
    {
      get { return _canAskfor; }
      set { _canAskfor = value; }
    }
    private int _giveNum = (int)0;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"giveNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int giveNum
    {
      get { return _giveNum; }
      set { _giveNum = value; }
    }
    private readonly global::System.Collections.Generic.List<StrengthGainInfo> _hasAskList = new global::System.Collections.Generic.List<StrengthGainInfo>();
    [global::ProtoBuf.ProtoMember(17, Name=@"hasAskList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<StrengthGainInfo> hasAskList
    {
      get { return _hasAskList; }
    }
  
    private readonly global::System.Collections.Generic.List<StrengthGainInfo> _gainList = new global::System.Collections.Generic.List<StrengthGainInfo>();
    [global::ProtoBuf.ProtoMember(18, Name=@"gainList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<StrengthGainInfo> gainList
    {
      get { return _gainList; }
    }
  
    private FriendStageInfo _stageInfo = null;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"stageInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FriendStageInfo stageInfo
    {
      get { return _stageInfo; }
      set { _stageInfo = value; }
    }
    private int _firendType = (int)0;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"firendType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int firendType
    {
      get { return _firendType; }
      set { _firendType = value; }
    }
    private int _isOpenExpedition = (int)0;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"isOpenExpedition", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int isOpenExpedition
    {
      get { return _isOpenExpedition; }
      set { _isOpenExpedition = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StrengthManagerInfo")]
  public partial class StrengthManagerInfo : global::ProtoBuf.IExtensible
  {
    public StrengthManagerInfo() {}
    
    private long _friendId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"friendId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long friendId
    {
      get { return _friendId; }
      set { _friendId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _hasAskList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"hasAskList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> hasAskList
    {
      get { return _hasAskList; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _gainList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"gainList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> gainList
    {
      get { return _gainList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StrengthGainInfo")]
  public partial class StrengthGainInfo : global::ProtoBuf.IExtensible
  {
    public StrengthGainInfo() {}
    
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private long _time = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long time
    {
      get { return _time; }
      set { _time = value; }
    }
    private int _state = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendStrength")]
  public partial class FriendStrength : global::ProtoBuf.IExtensible
  {
    public FriendStrength() {}
    
    private long _strengthId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"strengthId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long strengthId
    {
      get { return _strengthId; }
      set { _strengthId = value; }
    }
    private long _playerId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private int _playerLevel = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"playerLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playerLevel
    {
      get { return _playerLevel; }
      set { _playerLevel = value; }
    }
    private string _icon = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private string _playerName = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"playerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playerName
    {
      get { return _playerName; }
      set { _playerName = value; }
    }
    private string _sociatyName = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"sociatyName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sociatyName
    {
      get { return _sociatyName; }
      set { _sociatyName = value; }
    }
    private int _vipLevel = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"vipLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int vipLevel
    {
      get { return _vipLevel; }
      set { _vipLevel = value; }
    }
    private int _iconType = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"iconType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iconType
    {
      get { return _iconType; }
      set { _iconType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendStageInfo")]
  public partial class FriendStageInfo : global::ProtoBuf.IExtensible
  {
    public FriendStageInfo() {}
    
    private int _highStageId = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"highStageId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int highStageId
    {
      get { return _highStageId; }
      set { _highStageId = value; }
    }
    private int _starCount = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"starCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int starCount
    {
      get { return _starCount; }
      set { _starCount = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _stageIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"stageIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> stageIds
    {
      get { return _stageIds; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _stageScores = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"stageScores", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> stageScores
    {
      get { return _stageScores; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendPlafrom")]
  public partial class FriendPlafrom : global::ProtoBuf.IExtensible
  {
    public FriendPlafrom() {}
    
    private string _openId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"openId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string openId
    {
      get { return _openId; }
      set { _openId = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _icon;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SInviteFriendNotice")]
  public partial class C2SInviteFriendNotice : global::ProtoBuf.IExtensible
  {
    public C2SInviteFriendNotice() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CInviteFriendNotice")]
  public partial class S2CInviteFriendNotice : global::ProtoBuf.IExtensible
  {
    public S2CInviteFriendNotice() {}
    
    private bool _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CFriendStateChange")]
  public partial class S2CFriendStateChange : global::ProtoBuf.IExtensible
  {
    public S2CFriendStateChange() {}
    
    private long _friendId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"friendId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long friendId
    {
      get { return _friendId; }
      set { _friendId = value; }
    }
    private int _isOnline = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"isOnline", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int isOnline
    {
      get { return _isOnline; }
      set { _isOnline = value; }
    }
    private long _offlineTime = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"offlineTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long offlineTime
    {
      get { return _offlineTime; }
      set { _offlineTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}