//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: gameconfigure.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GAMECONFIGURE")]
  public partial class GAMECONFIGURE : global::ProtoBuf.IExtensible
  {
    public GAMECONFIGURE() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _inviteMax = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"inviteMax", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int inviteMax
    {
      get { return _inviteMax; }
      set { _inviteMax = value; }
    }
    private int _recordTimeout = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"recordTimeout", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int recordTimeout
    {
      get { return _recordTimeout; }
      set { _recordTimeout = value; }
    }
    private int _samplingRate = (int)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"samplingRate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int samplingRate
    {
      get { return _samplingRate; }
      set { _samplingRate = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GAMECONFIGURE_ARRAY")]
  public partial class GAMECONFIGURE_ARRAY : global::ProtoBuf.IExtensible
  {
    public GAMECONFIGURE_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.GAMECONFIGURE> _items = new global::System.Collections.Generic.List<deploy.GAMECONFIGURE>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.GAMECONFIGURE> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}