//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: gonghui_rizhi.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GONGHUI_RIZHI")]
  public partial class GONGHUI_RIZHI : global::ProtoBuf.IExtensible
  {
    public GONGHUI_RIZHI() {}
    
    private int _logid = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"logid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int logid
    {
      get { return _logid; }
      set { _logid = value; }
    }
    private int _content = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int content
    {
      get { return _content; }
      set { _content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GONGHUI_RIZHI_ARRAY")]
  public partial class GONGHUI_RIZHI_ARRAY : global::ProtoBuf.IExtensible
  {
    public GONGHUI_RIZHI_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.GONGHUI_RIZHI> _items = new global::System.Collections.Generic.List<deploy.GONGHUI_RIZHI>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.GONGHUI_RIZHI> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}