//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: gonghui_huizhang.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GONGHUI_HUIZHANG")]
  public partial class GONGHUI_HUIZHANG : global::ProtoBuf.IExtensible
  {
    public GONGHUI_HUIZHANG() {}
    
    private int _ziyuan_id = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ziyuan_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int ziyuan_id
    {
      get { return _ziyuan_id; }
      set { _ziyuan_id = value; }
    }
    private string _tuan_ziyuan = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tuan_ziyuan", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tuan_ziyuan
    {
      get { return _tuan_ziyuan; }
      set { _tuan_ziyuan = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GONGHUI_HUIZHANG_ARRAY")]
  public partial class GONGHUI_HUIZHANG_ARRAY : global::ProtoBuf.IExtensible
  {
    public GONGHUI_HUIZHANG_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.GONGHUI_HUIZHANG> _items = new global::System.Collections.Generic.List<deploy.GONGHUI_HUIZHANG>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.GONGHUI_HUIZHANG> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}