//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: gonghui_zhan.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GONGHUI_ZHAN")]
  public partial class GONGHUI_ZHAN : global::ProtoBuf.IExtensible
  {
    public GONGHUI_ZHAN() {}
    
    private int _ID = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _open_time = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"open_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string open_time
    {
      get { return _open_time; }
      set { _open_time = value; }
    }
    private string _close_time = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"close_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string close_time
    {
      get { return _close_time; }
      set { _close_time = value; }
    }
    private int _times = (int)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int times
    {
      get { return _times; }
      set { _times = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GONGHUI_ZHAN_ARRAY")]
  public partial class GONGHUI_ZHAN_ARRAY : global::ProtoBuf.IExtensible
  {
    public GONGHUI_ZHAN_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.GONGHUI_ZHAN> _items = new global::System.Collections.Generic.List<deploy.GONGHUI_ZHAN>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.GONGHUI_ZHAN> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}