//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: gonghui_lv_xianzhi.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GONGHUI_LV_XIANZHI")]
  public partial class GONGHUI_LV_XIANZHI : global::ProtoBuf.IExtensible
  {
    public GONGHUI_LV_XIANZHI() {}
    
    private int _if_id = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"if_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int if_id
    {
      get { return _if_id; }
      set { _if_id = value; }
    }
    private int _if_lv = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"if_lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int if_lv
    {
      get { return _if_lv; }
      set { _if_lv = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GONGHUI_LV_XIANZHI_ARRAY")]
  public partial class GONGHUI_LV_XIANZHI_ARRAY : global::ProtoBuf.IExtensible
  {
    public GONGHUI_LV_XIANZHI_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.GONGHUI_LV_XIANZHI> _items = new global::System.Collections.Generic.List<deploy.GONGHUI_LV_XIANZHI>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.GONGHUI_LV_XIANZHI> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}