//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: guide_bubble_config.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GUIDE_BUBBLE_CONFIG")]
  public partial class GUIDE_BUBBLE_CONFIG : global::ProtoBuf.IExtensible
  {
    public GUIDE_BUBBLE_CONFIG() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _group = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"group", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int group
    {
      get { return _group; }
      set { _group = value; }
    }
    private int _sort = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int sort
    {
      get { return _sort; }
      set { _sort = value; }
    }
    private int _text = (int)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"text", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int text
    {
      get { return _text; }
      set { _text = value; }
    }
    private int _conditionEvent1 = (int)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"conditionEvent1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int conditionEvent1
    {
      get { return _conditionEvent1; }
      set { _conditionEvent1 = value; }
    }
    private int _conditionEvent2 = (int)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"conditionEvent2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int conditionEvent2
    {
      get { return _conditionEvent2; }
      set { _conditionEvent2 = value; }
    }
    private int _conditionEvent3 = (int)0;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"conditionEvent3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int conditionEvent3
    {
      get { return _conditionEvent3; }
      set { _conditionEvent3 = value; }
    }
    private int _target = (int)0;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"target", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int target
    {
      get { return _target; }
      set { _target = value; }
    }
    private int _destorytype = (int)0;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"destorytype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int destorytype
    {
      get { return _destorytype; }
      set { _destorytype = value; }
    }
    private string _target_arg1 = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"target_arg1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string target_arg1
    {
      get { return _target_arg1; }
      set { _target_arg1 = value; }
    }
    private string _target_arg2 = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"target_arg2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string target_arg2
    {
      get { return _target_arg2; }
      set { _target_arg2 = value; }
    }
    private int _overturn = (int)0;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"overturn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int overturn
    {
      get { return _overturn; }
      set { _overturn = value; }
    }
    private string _detla_pos = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"detla_pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string detla_pos
    {
      get { return _detla_pos; }
      set { _detla_pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GUIDE_BUBBLE_CONFIG_ARRAY")]
  public partial class GUIDE_BUBBLE_CONFIG_ARRAY : global::ProtoBuf.IExtensible
  {
    public GUIDE_BUBBLE_CONFIG_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.GUIDE_BUBBLE_CONFIG> _items = new global::System.Collections.Generic.List<deploy.GUIDE_BUBBLE_CONFIG>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.GUIDE_BUBBLE_CONFIG> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}