//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: guide_config.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GUIDE_CONFIG")]
  public partial class GUIDE_CONFIG : global::ProtoBuf.IExtensible
  {
    public GUIDE_CONFIG() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _group = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"group", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int group
    {
      get { return _group; }
      set { _group = value; }
    }
    private int _sort = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int sort
    {
      get { return _sort; }
      set { _sort = value; }
    }
    private int _step = (int)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"step", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int step
    {
      get { return _step; }
      set { _step = value; }
    }
    private int _conditionEvent = (int)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"conditionEvent", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int conditionEvent
    {
      get { return _conditionEvent; }
      set { _conditionEvent = value; }
    }
    private int _target = (int)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"target", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int target
    {
      get { return _target; }
      set { _target = value; }
    }
    private string _target_arg1 = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"target_arg1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string target_arg1
    {
      get { return _target_arg1; }
      set { _target_arg1 = value; }
    }
    private string _target_arg2 = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"target_arg2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string target_arg2
    {
      get { return _target_arg2; }
      set { _target_arg2 = value; }
    }
    private int _preguidid = (int)0;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"preguidid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int preguidid
    {
      get { return _preguidid; }
      set { _preguidid = value; }
    }
    private int _showeffect = (int)0;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"showeffect", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int showeffect
    {
      get { return _showeffect; }
      set { _showeffect = value; }
    }
    private string _openDialog = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"openDialog", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string openDialog
    {
      get { return _openDialog; }
      set { _openDialog = value; }
    }
    private string _pos = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GUIDE_CONFIG_ARRAY")]
  public partial class GUIDE_CONFIG_ARRAY : global::ProtoBuf.IExtensible
  {
    public GUIDE_CONFIG_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.GUIDE_CONFIG> _items = new global::System.Collections.Generic.List<deploy.GUIDE_CONFIG>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.GUIDE_CONFIG> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}