//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: HeroMsg.proto
// Note: requires additional types generated from: GuildMsg.proto
using GuildMsg;
namespace HeroMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SCreateHero")]
  public partial class C2SCreateHero : global::ProtoBuf.IExtensible
  {
    public C2SCreateHero() {}
    
    private int _heroId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroId
    {
      get { return _heroId; }
      set { _heroId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SHeroUpSkill")]
  public partial class C2SHeroUpSkill : global::ProtoBuf.IExtensible
  {
    public C2SHeroUpSkill() {}
    
    private int _heroId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroId
    {
      get { return _heroId; }
      set { _heroId = value; }
    }
    private int _skillId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillId
    {
      get { return _skillId; }
      set { _skillId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CHeroUpSkill")]
  public partial class S2CHeroUpSkill : global::ProtoBuf.IExtensible
  {
    public S2CHeroUpSkill() {}
    
    private int _heroId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroId
    {
      get { return _heroId; }
      set { _heroId = value; }
    }
    private int _skillId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillId
    {
      get { return _skillId; }
      set { _skillId = value; }
    }
    private int _skillLevel;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"skillLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillLevel
    {
      get { return _skillLevel; }
      set { _skillLevel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SHeroUpStar")]
  public partial class C2SHeroUpStar : global::ProtoBuf.IExtensible
  {
    public C2SHeroUpStar() {}
    
    private int _heroId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroId
    {
      get { return _heroId; }
      set { _heroId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CHeroUpStar")]
  public partial class S2CHeroUpStar : global::ProtoBuf.IExtensible
  {
    public S2CHeroUpStar() {}
    
    private int _heroId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroId
    {
      get { return _heroId; }
      set { _heroId = value; }
    }
    private int _star;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int star
    {
      get { return _star; }
      set { _star = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SHeroChangeCamp")]
  public partial class C2SHeroChangeCamp : global::ProtoBuf.IExtensible
  {
    public C2SHeroChangeCamp() {}
    
    private int _campId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"campId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int campId
    {
      get { return _campId; }
      set { _campId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _heroIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"heroIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> heroIds
    {
      get { return _heroIds; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CHeroSingleCamp")]
  public partial class S2CHeroSingleCamp : global::ProtoBuf.IExtensible
  {
    public S2CHeroSingleCamp() {}
    
    private int _campId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"campId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int campId
    {
      get { return _campId; }
      set { _campId = value; }
    }
    private readonly global::System.Collections.Generic.List<HeroCamp> _camp = new global::System.Collections.Generic.List<HeroCamp>();
    [global::ProtoBuf.ProtoMember(2, Name=@"camp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<HeroCamp> camp
    {
      get { return _camp; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SHeroDefaultCamp")]
  public partial class C2SHeroDefaultCamp : global::ProtoBuf.IExtensible
  {
    public C2SHeroDefaultCamp() {}
    
    private int _campId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"campId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int campId
    {
      get { return _campId; }
      set { _campId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CHeroDefaultCamp")]
  public partial class S2CHeroDefaultCamp : global::ProtoBuf.IExtensible
  {
    public S2CHeroDefaultCamp() {}
    
    private int _campId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"campId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int campId
    {
      get { return _campId; }
      set { _campId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SHeroUpPhaseLevel")]
  public partial class C2SHeroUpPhaseLevel : global::ProtoBuf.IExtensible
  {
    public C2SHeroUpPhaseLevel() {}
    
    private int _heroId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroId
    {
      get { return _heroId; }
      set { _heroId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CHeroUpHpaseLevel")]
  public partial class S2CHeroUpHpaseLevel : global::ProtoBuf.IExtensible
  {
    public S2CHeroUpHpaseLevel() {}
    
    private int _phaseLevel;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"phaseLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int phaseLevel
    {
      get { return _phaseLevel; }
      set { _phaseLevel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SHeroUpOfficeLevel")]
  public partial class C2SHeroUpOfficeLevel : global::ProtoBuf.IExtensible
  {
    public C2SHeroUpOfficeLevel() {}
    
    private int _heroId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroId
    {
      get { return _heroId; }
      set { _heroId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CHeroUpOfficeLevel")]
  public partial class S2CHeroUpOfficeLevel : global::ProtoBuf.IExtensible
  {
    public S2CHeroUpOfficeLevel() {}
    
    private int _officeLevel;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"officeLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int officeLevel
    {
      get { return _officeLevel; }
      set { _officeLevel = value; }
    }
    private int _officeExp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"officeExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int officeExp
    {
      get { return _officeExp; }
      set { _officeExp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SHeroUpLevel")]
  public partial class C2SHeroUpLevel : global::ProtoBuf.IExtensible
  {
    public C2SHeroUpLevel() {}
    
    private int _heroId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroId
    {
      get { return _heroId; }
      set { _heroId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CHeroUpLevel")]
  public partial class S2CHeroUpLevel : global::ProtoBuf.IExtensible
  {
    public S2CHeroUpLevel() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _nextLv = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"nextLv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int nextLv
    {
      get { return _nextLv; }
      set { _nextLv = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SNewHeroClick")]
  public partial class C2SNewHeroClick : global::ProtoBuf.IExtensible
  {
    public C2SNewHeroClick() {}
    
    private int _heroId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroId
    {
      get { return _heroId; }
      set { _heroId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CNewHeroClick")]
  public partial class S2CNewHeroClick : global::ProtoBuf.IExtensible
  {
    public S2CNewHeroClick() {}
    
    private int _heroId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroId
    {
      get { return _heroId; }
      set { _heroId = value; }
    }
    private int _isNew;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"isNew", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int isNew
    {
      get { return _isNew; }
      set { _isNew = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}