//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: hero_chou.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HERO_CHOU")]
  public partial class HERO_CHOU : global::ProtoBuf.IExtensible
  {
    public HERO_CHOU() {}
    
    private int _chou_id = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"chou_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int chou_id
    {
      get { return _chou_id; }
      set { _chou_id = value; }
    }
    private int _money_type = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"money_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int money_type
    {
      get { return _money_type; }
      set { _money_type = value; }
    }
    private int _price = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int price
    {
      get { return _price; }
      set { _price = value; }
    }
    private int _count = (int)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private int _basis_item = (int)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"basis_item", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int basis_item
    {
      get { return _basis_item; }
      set { _basis_item = value; }
    }
    private int _name = (int)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _show_card = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"show_card", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string show_card
    {
      get { return _show_card; }
      set { _show_card = value; }
    }
    private int _show_card_total = (int)0;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"show_card_total", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int show_card_total
    {
      get { return _show_card_total; }
      set { _show_card_total = value; }
    }
    private string _show_gold_range = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"show_gold_range", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string show_gold_range
    {
      get { return _show_gold_range; }
      set { _show_gold_range = value; }
    }
    private string _describe = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"describe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string describe
    {
      get { return _describe; }
      set { _describe = value; }
    }
    private string _first_show_card = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"first_show_card", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string first_show_card
    {
      get { return _first_show_card; }
      set { _first_show_card = value; }
    }
    private int _first_card_total = (int)0;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"first_card_total", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int first_card_total
    {
      get { return _first_card_total; }
      set { _first_card_total = value; }
    }
    private int _mianfei = (int)0;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"mianfei", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int mianfei
    {
      get { return _mianfei; }
      set { _mianfei = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HERO_CHOU_ARRAY")]
  public partial class HERO_CHOU_ARRAY : global::ProtoBuf.IExtensible
  {
    public HERO_CHOU_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.HERO_CHOU> _items = new global::System.Collections.Generic.List<deploy.HERO_CHOU>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.HERO_CHOU> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}