//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: hero_order.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HERO_ORDER")]
  public partial class HERO_ORDER : global::ProtoBuf.IExtensible
  {
    public HERO_ORDER() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _order_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"order_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string order_name
    {
      get { return _order_name; }
      set { _order_name = value; }
    }
    private int _lv = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int lv
    {
      get { return _lv; }
      set { _lv = value; }
    }
    private int _gold = (int)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private string _shield_material = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"shield_material", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string shield_material
    {
      get { return _shield_material; }
      set { _shield_material = value; }
    }
    private string _warrior_material = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"warrior_material", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string warrior_material
    {
      get { return _warrior_material; }
      set { _warrior_material = value; }
    }
    private string _master_material = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"master_material", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string master_material
    {
      get { return _master_material; }
      set { _master_material = value; }
    }
    private string _assassin_material = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"assassin_material", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string assassin_material
    {
      get { return _assassin_material; }
      set { _assassin_material = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HERO_ORDER_ARRAY")]
  public partial class HERO_ORDER_ARRAY : global::ProtoBuf.IExtensible
  {
    public HERO_ORDER_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.HERO_ORDER> _items = new global::System.Collections.Generic.List<deploy.HERO_ORDER>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.HERO_ORDER> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}