//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: hero_email.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HERO_EMAIL")]
  public partial class HERO_EMAIL : global::ProtoBuf.IExtensible
  {
    public HERO_EMAIL() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _title = (uint)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint title
    {
      get { return _title; }
      set { _title = value; }
    }
    private uint _content = (uint)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint content
    {
      get { return _content; }
      set { _content = value; }
    }
    private uint _sendName = (uint)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sendName", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint sendName
    {
      get { return _sendName; }
      set { _sendName = value; }
    }
    private int _accessory = (int)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"accessory", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int accessory
    {
      get { return _accessory; }
      set { _accessory = value; }
    }
    private uint _expireTime = (uint)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"expireTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint expireTime
    {
      get { return _expireTime; }
      set { _expireTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HERO_EMAIL_ARRAY")]
  public partial class HERO_EMAIL_ARRAY : global::ProtoBuf.IExtensible
  {
    public HERO_EMAIL_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.HERO_EMAIL> _items = new global::System.Collections.Generic.List<deploy.HERO_EMAIL>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.HERO_EMAIL> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}