//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: huiliu.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HUILIU")]
  public partial class HUILIU : global::ProtoBuf.IExtensible
  {
    public HUILIU() {}
    
    private int _day = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"day", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int day
    {
      get { return _day; }
      set { _day = value; }
    }
    private string _rewards = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string rewards
    {
      get { return _rewards; }
      set { _rewards = value; }
    }
    private int _rewards_content = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"rewards_content", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int rewards_content
    {
      get { return _rewards_content; }
      set { _rewards_content = value; }
    }
    private string _rewards_times = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"rewards_times", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string rewards_times
    {
      get { return _rewards_times; }
      set { _rewards_times = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HUILIU_ARRAY")]
  public partial class HUILIU_ARRAY : global::ProtoBuf.IExtensible
  {
    public HUILIU_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.HUILIU> _items = new global::System.Collections.Generic.List<deploy.HUILIU>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.HUILIU> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}