//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: huodong.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HUODONG")]
  public partial class HUODONG : global::ProtoBuf.IExtensible
  {
    public HUODONG() {}
    
    private int _id = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _name = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _tips = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int tips
    {
      get { return _tips; }
      set { _tips = value; }
    }
    private int _open;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"open", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int open
    {
      get { return _open; }
      set { _open = value; }
    }
    private int _time = (int)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }
    private int _time_open = (int)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"time_open", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int time_open
    {
      get { return _time_open; }
      set { _time_open = value; }
    }
    private int _time_end = (int)0;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"time_end", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int time_end
    {
      get { return _time_end; }
      set { _time_end = value; }
    }
    private int _maxPurchaseTimes = (int)0;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"maxPurchaseTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int maxPurchaseTimes
    {
      get { return _maxPurchaseTimes; }
      set { _maxPurchaseTimes = value; }
    }
    private string _productID = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"productID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string productID
    {
      get { return _productID; }
      set { _productID = value; }
    }
    private int _rmb = (int)0;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"rmb", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int rmb
    {
      get { return _rmb; }
      set { _rmb = value; }
    }
    private int _hkd = (int)0;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"hkd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int hkd
    {
      get { return _hkd; }
      set { _hkd = value; }
    }
    private int _twd = (int)0;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"twd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int twd
    {
      get { return _twd; }
      set { _twd = value; }
    }
    private int _myr = (int)0;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"myr", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int myr
    {
      get { return _myr; }
      set { _myr = value; }
    }
    private int _sgd = (int)0;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"sgd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int sgd
    {
      get { return _sgd; }
      set { _sgd = value; }
    }
    private string _jodo_productId = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"jodo_productId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jodo_productId
    {
      get { return _jodo_productId; }
      set { _jodo_productId = value; }
    }
    private int _jodo_price = (int)0;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"jodo_price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int jodo_price
    {
      get { return _jodo_price; }
      set { _jodo_price = value; }
    }
    private string _MY = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"MY", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string MY
    {
      get { return _MY; }
      set { _MY = value; }
    }
    private string _HKD = "";
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"HKD", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string HKD
    {
      get { return _HKD; }
      set { _HKD = value; }
    }
    private string _TWD = "";
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"TWD", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string TWD
    {
      get { return _TWD; }
      set { _TWD = value; }
    }
    private string _MYR = "";
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"MYR", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string MYR
    {
      get { return _MYR; }
      set { _MYR = value; }
    }
    private string _SGD = "";
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"SGD", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SGD
    {
      get { return _SGD; }
      set { _SGD = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HUODONG_ARRAY")]
  public partial class HUODONG_ARRAY : global::ProtoBuf.IExtensible
  {
    public HUODONG_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.HUODONG> _items = new global::System.Collections.Generic.List<deploy.HUODONG>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.HUODONG> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}