//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: invite.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"INVITE")]
  public partial class INVITE : global::ProtoBuf.IExtensible
  {
    public INVITE() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _reward_id = (uint)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reward_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint reward_id
    {
      get { return _reward_id; }
      set { _reward_id = value; }
    }
    private int _diamond = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private uint _all_id = (uint)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"all_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint all_id
    {
      get { return _all_id; }
      set { _all_id = value; }
    }
    private int _all_diamond = (int)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"all_diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int all_diamond
    {
      get { return _all_diamond; }
      set { _all_diamond = value; }
    }
    private int _gold_id = (int)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"gold_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int gold_id
    {
      get { return _gold_id; }
      set { _gold_id = value; }
    }
    private int _invite_money = (int)0;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"invite_money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int invite_money
    {
      get { return _invite_money; }
      set { _invite_money = value; }
    }
    private int _money = (int)0;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int money
    {
      get { return _money; }
      set { _money = value; }
    }
    private string _link = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"link", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string link
    {
      get { return _link; }
      set { _link = value; }
    }
    private int _invite_title = (int)0;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"invite_title", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int invite_title
    {
      get { return _invite_title; }
      set { _invite_title = value; }
    }
    private int _invite = (int)0;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"invite", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int invite
    {
      get { return _invite; }
      set { _invite = value; }
    }
    private string _imageurl = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"imageurl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string imageurl
    {
      get { return _imageurl; }
      set { _imageurl = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"INVITE_ARRAY")]
  public partial class INVITE_ARRAY : global::ProtoBuf.IExtensible
  {
    public INVITE_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.INVITE> _items = new global::System.Collections.Generic.List<deploy.INVITE>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.INVITE> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}