//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: loading.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LOADING")]
  public partial class LOADING : global::ProtoBuf.IExtensible
  {
    public LOADING() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _atlas_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"atlas_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int atlas_id
    {
      get { return _atlas_id; }
      set { _atlas_id = value; }
    }
    private string _icon = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private int _tips = (int)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"tips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int tips
    {
      get { return _tips; }
      set { _tips = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LOADING_ARRAY")]
  public partial class LOADING_ARRAY : global::ProtoBuf.IExtensible
  {
    public LOADING_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.LOADING> _items = new global::System.Collections.Generic.List<deploy.LOADING>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.LOADING> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}