//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: log_on.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LOG_ON")]
  public partial class LOG_ON : global::ProtoBuf.IExtensible
  {
    public LOG_ON() {}
    
    private int _days = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"days", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int days
    {
      get { return _days; }
      set { _days = value; }
    }
    private int _icon = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private int _type = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _rewards = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"rewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string rewards
    {
      get { return _rewards; }
      set { _rewards = value; }
    }
    private int _describe = (int)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"describe", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int describe
    {
      get { return _describe; }
      set { _describe = value; }
    }
    private int _effect = (int)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"effect", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int effect
    {
      get { return _effect; }
      set { _effect = value; }
    }
    private int _vip = (int)0;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"vip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int vip
    {
      get { return _vip; }
      set { _vip = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LOG_ON_ARRAY")]
  public partial class LOG_ON_ARRAY : global::ProtoBuf.IExtensible
  {
    public LOG_ON_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.LOG_ON> _items = new global::System.Collections.Generic.List<deploy.LOG_ON>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.LOG_ON> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}