//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: onedollar.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ONEDOLLAR")]
  public partial class ONEDOLLAR : global::ProtoBuf.IExtensible
  {
    public ONEDOLLAR() {}
    
    private int _id = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _rewards = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string rewards
    {
      get { return _rewards; }
      set { _rewards = value; }
    }
    private int _name = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _icon = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private int _time = (int)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }
    private int _probability = (int)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"probability", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int probability
    {
      get { return _probability; }
      set { _probability = value; }
    }
    private int _open = (int)0;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"open", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int open
    {
      get { return _open; }
      set { _open = value; }
    }
    private int _dialog = (int)0;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"dialog", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int dialog
    {
      get { return _dialog; }
      set { _dialog = value; }
    }
    private int _rewards_type = (int)0;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"rewards_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int rewards_type
    {
      get { return _rewards_type; }
      set { _rewards_type = value; }
    }
    private string _rewards_bag = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"rewards_bag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string rewards_bag
    {
      get { return _rewards_bag; }
      set { _rewards_bag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ONEDOLLAR_ARRAY")]
  public partial class ONEDOLLAR_ARRAY : global::ProtoBuf.IExtensible
  {
    public ONEDOLLAR_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.ONEDOLLAR> _items = new global::System.Collections.Generic.List<deploy.ONEDOLLAR>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.ONEDOLLAR> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}