//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: patrol.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PATROL")]
  public partial class PATROL : global::ProtoBuf.IExtensible
  {
    public PATROL() {}
    
    private int _task_id = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"task_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int task_id
    {
      get { return _task_id; }
      set { _task_id = value; }
    }
    private int _task_lv = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"task_lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int task_lv
    {
      get { return _task_lv; }
      set { _task_lv = value; }
    }
    private string _task_name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"task_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string task_name
    {
      get { return _task_name; }
      set { _task_name = value; }
    }
    private int _task_type = (int)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"task_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int task_type
    {
      get { return _task_type; }
      set { _task_type = value; }
    }
    private int _hero_time = (int)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"hero_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int hero_time
    {
      get { return _hero_time; }
      set { _hero_time = value; }
    }
    private int _mission_level = (int)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"mission_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int mission_level
    {
      get { return _mission_level; }
      set { _mission_level = value; }
    }
    private string _hero_type = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"hero_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hero_type
    {
      get { return _hero_type; }
      set { _hero_type = value; }
    }
    private int _fight = (int)0;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"fight", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int fight
    {
      get { return _fight; }
      set { _fight = value; }
    }
    private int _hero_amounts = (int)0;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"hero_amounts", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int hero_amounts
    {
      get { return _hero_amounts; }
      set { _hero_amounts = value; }
    }
    private int _money = (int)0;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int money
    {
      get { return _money; }
      set { _money = value; }
    }
    private int _diamond = (int)0;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private int _xunluo_money = (int)0;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"xunluo_money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int xunluo_money
    {
      get { return _xunluo_money; }
      set { _xunluo_money = value; }
    }
    private ulong _item_id1 = (ulong)0;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"item_id1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)0)]
    public ulong item_id1
    {
      get { return _item_id1; }
      set { _item_id1 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PATROL_ARRAY")]
  public partial class PATROL_ARRAY : global::ProtoBuf.IExtensible
  {
    public PATROL_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.PATROL> _items = new global::System.Collections.Generic.List<deploy.PATROL>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.PATROL> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}