//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: PayMsg.proto
namespace PayMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SGeneratePaySerial")]
  public partial class C2SGeneratePaySerial : global::ProtoBuf.IExtensible
  {
    public C2SGeneratePaySerial() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CGeneratePaySerial")]
  public partial class S2CGeneratePaySerial : global::ProtoBuf.IExtensible
  {
    public S2CGeneratePaySerial() {}
    
    private string _serialNo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"serialNo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string serialNo
    {
      get { return _serialNo; }
      set { _serialNo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SSyncSubmitPayOrder")]
  public partial class C2SSyncSubmitPayOrder : global::ProtoBuf.IExtensible
  {
    public C2SSyncSubmitPayOrder() {}
    
    private string _signature;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"signature", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string signature
    {
      get { return _signature; }
      set { _signature = value; }
    }
    private string _signData;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"signData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string signData
    {
      get { return _signData; }
      set { _signData = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CSyncSubmitPayOrder")]
  public partial class S2CSyncSubmitPayOrder : global::ProtoBuf.IExtensible
  {
    public S2CSyncSubmitPayOrder() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _diamond = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}