//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: pvp_ranking.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PVP_RANKING")]
  public partial class PVP_RANKING : global::ProtoBuf.IExtensible
  {
    public PVP_RANKING() {}
    
    private string _rank_id = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"rank_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string rank_id
    {
      get { return _rank_id; }
      set { _rank_id = value; }
    }
    private int _gold_award = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gold_award", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int gold_award
    {
      get { return _gold_award; }
      set { _gold_award = value; }
    }
    private int _diamond_award = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"diamond_award", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int diamond_award
    {
      get { return _diamond_award; }
      set { _diamond_award = value; }
    }
    private int _honors = (int)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"honors", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int honors
    {
      get { return _honors; }
      set { _honors = value; }
    }
    private int _bonus = (int)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"bonus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int bonus
    {
      get { return _bonus; }
      set { _bonus = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PVP_RANKING_ARRAY")]
  public partial class PVP_RANKING_ARRAY : global::ProtoBuf.IExtensible
  {
    public PVP_RANKING_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.PVP_RANKING> _items = new global::System.Collections.Generic.List<deploy.PVP_RANKING>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.PVP_RANKING> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}