//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: pvp_data.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PVP_DATA")]
  public partial class PVP_DATA : global::ProtoBuf.IExtensible
  {
    public PVP_DATA() {}
    
    private int _event_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"event_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int event_id
    {
      get { return _event_id; }
      set { _event_id = value; }
    }
    private string _event_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"event_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string event_name
    {
      get { return _event_name; }
      set { _event_name = value; }
    }
    private int _event_type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"event_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int event_type
    {
      get { return _event_type; }
      set { _event_type = value; }
    }
    private int _event_refresh_time;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"event_refresh_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int event_refresh_time
    {
      get { return _event_refresh_time; }
      set { _event_refresh_time = value; }
    }
    private int _event_occurrence_probability;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"event_occurrence_probability", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int event_occurrence_probability
    {
      get { return _event_occurrence_probability; }
      set { _event_occurrence_probability = value; }
    }
    private int _event_duration_time;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"event_duration_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int event_duration_time
    {
      get { return _event_duration_time; }
      set { _event_duration_time = value; }
    }
    private int _events_well;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"events_well", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int events_well
    {
      get { return _events_well; }
      set { _events_well = value; }
    }
    private int _effect_value;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"effect_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int effect_value
    {
      get { return _effect_value; }
      set { _effect_value = value; }
    }
    private readonly global::System.Collections.Generic.List<deploy.PVP_DATA.Item> _ItemTable = new global::System.Collections.Generic.List<deploy.PVP_DATA.Item>();
    [global::ProtoBuf.ProtoMember(9, Name=@"ItemTable", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.PVP_DATA.Item> ItemTable
    {
      get { return _ItemTable; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Item")]
  public partial class Item : global::ProtoBuf.IExtensible
  {
    public Item() {}
    
    private int _reward = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int reward
    {
      get { return _reward; }
      set { _reward = value; }
    }
    private int _reward_value = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reward_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int reward_value
    {
      get { return _reward_value; }
      set { _reward_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PVP_DATA_ARRAY")]
  public partial class PVP_DATA_ARRAY : global::ProtoBuf.IExtensible
  {
    public PVP_DATA_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.PVP_DATA> _items = new global::System.Collections.Generic.List<deploy.PVP_DATA>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.PVP_DATA> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}