//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: pvp_warehouse.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PVP_WAREHOUSE")]
  public partial class PVP_WAREHOUSE : global::ProtoBuf.IExtensible
  {
    public PVP_WAREHOUSE() {}
    
    private int _warehouse_level;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"warehouse_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int warehouse_level
    {
      get { return _warehouse_level; }
      set { _warehouse_level = value; }
    }
    private int _consumption = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"consumption", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int consumption
    {
      get { return _consumption; }
      set { _consumption = value; }
    }
    private int _gold_max = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"gold_max", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int gold_max
    {
      get { return _gold_max; }
      set { _gold_max = value; }
    }
    private int _diamond_max = (int)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"diamond_max", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int diamond_max
    {
      get { return _diamond_max; }
      set { _diamond_max = value; }
    }
    private int _experience_max = (int)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"experience_max", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int experience_max
    {
      get { return _experience_max; }
      set { _experience_max = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PVP_WAREHOUSE_ARRAY")]
  public partial class PVP_WAREHOUSE_ARRAY : global::ProtoBuf.IExtensible
  {
    public PVP_WAREHOUSE_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.PVP_WAREHOUSE> _items = new global::System.Collections.Generic.List<deploy.PVP_WAREHOUSE>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.PVP_WAREHOUSE> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}