//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: pvp_option.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PVP_OPTION")]
  public partial class PVP_OPTION : global::ProtoBuf.IExtensible
  {
    public PVP_OPTION() {}
    
    private int _playerlevel;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerlevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerlevel
    {
      get { return _playerlevel; }
      set { _playerlevel = value; }
    }
    private int _time_parameter;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"time_parameter", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int time_parameter
    {
      get { return _time_parameter; }
      set { _time_parameter = value; }
    }
    private int _integral_demand;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"integral_demand", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int integral_demand
    {
      get { return _integral_demand; }
      set { _integral_demand = value; }
    }
    private int _the_upper_chest = (int)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"the_upper_chest", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int the_upper_chest
    {
      get { return _the_upper_chest; }
      set { _the_upper_chest = value; }
    }
    private int _chest_refresh_probability = (int)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"chest_refresh_probability", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int chest_refresh_probability
    {
      get { return _chest_refresh_probability; }
      set { _chest_refresh_probability = value; }
    }
    private int _military_orders = (int)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"military_orders", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int military_orders
    {
      get { return _military_orders; }
      set { _military_orders = value; }
    }
    private int _limit_orders = (int)0;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"limit_orders", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int limit_orders
    {
      get { return _limit_orders; }
      set { _limit_orders = value; }
    }
    private int _chest_reward = (int)0;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"chest_reward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int chest_reward
    {
      get { return _chest_reward; }
      set { _chest_reward = value; }
    }
    private float _chest_reward_up = (float)0;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"chest_reward_up", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float chest_reward_up
    {
      get { return _chest_reward_up; }
      set { _chest_reward_up = value; }
    }
    private int _chest_reward_max = (int)0;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"chest_reward_max", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int chest_reward_max
    {
      get { return _chest_reward_max; }
      set { _chest_reward_max = value; }
    }
    private int _chest_reward_crit = (int)0;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"chest_reward_crit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int chest_reward_crit
    {
      get { return _chest_reward_crit; }
      set { _chest_reward_crit = value; }
    }
    private int _attack_time = (int)0;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"attack_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int attack_time
    {
      get { return _attack_time; }
      set { _attack_time = value; }
    }
    private int _honor_currency = (int)0;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"honor_currency", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int honor_currency
    {
      get { return _honor_currency; }
      set { _honor_currency = value; }
    }
    private int _auto_refresh = (int)0;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"auto_refresh", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int auto_refresh
    {
      get { return _auto_refresh; }
      set { _auto_refresh = value; }
    }
    private int _daytime = (int)0;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"daytime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int daytime
    {
      get { return _daytime; }
      set { _daytime = value; }
    }
    private int _night = (int)0;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"night", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int night
    {
      get { return _night; }
      set { _night = value; }
    }
    private float _force_coefficient_max = (float)0;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"force_coefficient_max", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float force_coefficient_max
    {
      get { return _force_coefficient_max; }
      set { _force_coefficient_max = value; }
    }
    private float _force_coefficient_min = (float)0;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"force_coefficient_min", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float force_coefficient_min
    {
      get { return _force_coefficient_min; }
      set { _force_coefficient_min = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PVP_OPTION_ARRAY")]
  public partial class PVP_OPTION_ARRAY : global::ProtoBuf.IExtensible
  {
    public PVP_OPTION_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.PVP_OPTION> _items = new global::System.Collections.Generic.List<deploy.PVP_OPTION>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.PVP_OPTION> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}