//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SecretMsg.proto
// Note: requires additional types generated from: GuildMsg.proto

using GuildMsg;
namespace SecretMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SOnlineSecretMembers")]
  public partial class C2SOnlineSecretMembers : global::ProtoBuf.IExtensible
  {
    public C2SOnlineSecretMembers() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2COnlineSecretMembers")]
  public partial class S2COnlineSecretMembers : global::ProtoBuf.IExtensible
  {
    public S2COnlineSecretMembers() {}
    
    private readonly global::System.Collections.Generic.List<SecretMemberInfo> _memberList = new global::System.Collections.Generic.List<SecretMemberInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"memberList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SecretMemberInfo> memberList
    {
      get { return _memberList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SCreateSecretRoom")]
  public partial class C2SCreateSecretRoom : global::ProtoBuf.IExtensible
  {
    public C2SCreateSecretRoom() {}
    
    private int _chapterId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"chapterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int chapterId
    {
      get { return _chapterId; }
      set { _chapterId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CCreateSecretRoom")]
  public partial class S2CCreateSecretRoom : global::ProtoBuf.IExtensible
  {
    public S2CCreateSecretRoom() {}
    
    private int _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private int _chapterId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"chapterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int chapterId
    {
      get { return _chapterId; }
      set { _chapterId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SGetSecretMembers")]
  public partial class C2SGetSecretMembers : global::ProtoBuf.IExtensible
  {
    public C2SGetSecretMembers() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CGetSecretMembers")]
  public partial class S2CGetSecretMembers : global::ProtoBuf.IExtensible
  {
    public S2CGetSecretMembers() {}
    
    private int _chapterId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"chapterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int chapterId
    {
      get { return _chapterId; }
      set { _chapterId = value; }
    }
    private long _captainId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"captainId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long captainId
    {
      get { return _captainId; }
      set { _captainId = value; }
    }
    private long _closeTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"closeTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long closeTime
    {
      get { return _closeTime; }
      set { _closeTime = value; }
    }
    private readonly global::System.Collections.Generic.List<SecretMemberInfo> _memberList = new global::System.Collections.Generic.List<SecretMemberInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"memberList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SecretMemberInfo> memberList
    {
      get { return _memberList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SSecretInviteMember")]
  public partial class C2SSecretInviteMember : global::ProtoBuf.IExtensible
  {
    public C2SSecretInviteMember() {}
    
    private long _memberId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"memberId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long memberId
    {
      get { return _memberId; }
      set { _memberId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CSecretInviteMember")]
  public partial class S2CSecretInviteMember : global::ProtoBuf.IExtensible
  {
    public S2CSecretInviteMember() {}
    
    private readonly global::System.Collections.Generic.List<int> _results = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"results", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> results
    {
      get { return _results; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _memberIds = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(2, Name=@"memberIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> memberIds
    {
      get { return _memberIds; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _cdTimes = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(3, Name=@"cdTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> cdTimes
    {
      get { return _cdTimes; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SAgreeJoinSecret")]
  public partial class C2SAgreeJoinSecret : global::ProtoBuf.IExtensible
  {
    public C2SAgreeJoinSecret() {}
    
    private int _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private int _opType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"opType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int opType
    {
      get { return _opType; }
      set { _opType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CAgreeJoinSecret")]
  public partial class S2CAgreeJoinSecret : global::ProtoBuf.IExtensible
  {
    public S2CAgreeJoinSecret() {}
    
    private int _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private int _opType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"opType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int opType
    {
      get { return _opType; }
      set { _opType = value; }
    }
    private int _result = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _chapterId = (int)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"chapterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int chapterId
    {
      get { return _chapterId; }
      set { _chapterId = value; }
    }
    private long _captainId = (long)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"captainId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)0)]
    public long captainId
    {
      get { return _captainId; }
      set { _captainId = value; }
    }
    private long _closeTime = (long)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"closeTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((long)0)]
    public long closeTime
    {
      get { return _closeTime; }
      set { _closeTime = value; }
    }
    private readonly global::System.Collections.Generic.List<SecretMemberInfo> _memberList = new global::System.Collections.Generic.List<SecretMemberInfo>();
    [global::ProtoBuf.ProtoMember(7, Name=@"memberList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SecretMemberInfo> memberList
    {
      get { return _memberList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SSecretKickMember")]
  public partial class C2SSecretKickMember : global::ProtoBuf.IExtensible
  {
    public C2SSecretKickMember() {}
    
    private int _memberId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"memberId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int memberId
    {
      get { return _memberId; }
      set { _memberId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CSecretKickMember")]
  public partial class S2CSecretKickMember : global::ProtoBuf.IExtensible
  {
    public S2CSecretKickMember() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SSecretMemberQuit")]
  public partial class C2SSecretMemberQuit : global::ProtoBuf.IExtensible
  {
    public C2SSecretMemberQuit() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CSecretMemberQuit")]
  public partial class S2CSecretMemberQuit : global::ProtoBuf.IExtensible
  {
    public S2CSecretMemberQuit() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CSecretMemberChange")]
  public partial class S2CSecretMemberChange : global::ProtoBuf.IExtensible
  {
    public S2CSecretMemberChange() {}
    
    private int _change;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"change", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int change
    {
      get { return _change; }
      set { _change = value; }
    }
    private SecretMemberInfo _memberInfo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"memberInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public SecretMemberInfo memberInfo
    {
      get { return _memberInfo; }
      set { _memberInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SSecretFightStart")]
  public partial class C2SSecretFightStart : global::ProtoBuf.IExtensible
  {
    public C2SSecretFightStart() {}
    
    private int _stageId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"stageId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stageId
    {
      get { return _stageId; }
      set { _stageId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _heroIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"heroIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> heroIds
    {
      get { return _heroIds; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CSecretFightStart")]
  public partial class S2CSecretFightStart : global::ProtoBuf.IExtensible
  {
    public S2CSecretFightStart() {}
    
    private long _fightId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fightId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long fightId
    {
      get { return _fightId; }
      set { _fightId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SSecretFightEnd")]
  public partial class C2SSecretFightEnd : global::ProtoBuf.IExtensible
  {
    public C2SSecretFightEnd() {}
    
    private long _fightId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fightId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long fightId
    {
      get { return _fightId; }
      set { _fightId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _heroIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"heroIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> heroIds
    {
      get { return _heroIds; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _heroHps = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(3, Name=@"heroHps", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> heroHps
    {
      get { return _heroHps; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _enemyIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"enemyIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> enemyIds
    {
      get { return _enemyIds; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _enemyHps = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(5, Name=@"enemyHps", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> enemyHps
    {
      get { return _enemyHps; }
    }
  
    private FightResultParam _resultParam;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"resultParam", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public FightResultParam resultParam
    {
      get { return _resultParam; }
      set { _resultParam = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CSecretFightEnd")]
  public partial class S2CSecretFightEnd : global::ProtoBuf.IExtensible
  {
    public S2CSecretFightEnd() {}
    
    private long _fightId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fightId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long fightId
    {
      get { return _fightId; }
      set { _fightId = value; }
    }
    private FightResultType _result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public FightResultType result
    {
      get { return _result; }
      set { _result = value; }
    }
    private DropReward _reward;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public DropReward reward
    {
      get { return _reward; }
      set { _reward = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SSecretRoomOpen")]
  public partial class C2SSecretRoomOpen : global::ProtoBuf.IExtensible
  {
    public C2SSecretRoomOpen() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CSecretRoomOpen")]
  public partial class S2CSecretRoomOpen : global::ProtoBuf.IExtensible
  {
    public S2CSecretRoomOpen() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SSecretRoomClose")]
  public partial class C2SSecretRoomClose : global::ProtoBuf.IExtensible
  {
    public C2SSecretRoomClose() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CSecretRoomClose")]
  public partial class S2CSecretRoomClose : global::ProtoBuf.IExtensible
  {
    public S2CSecretRoomClose() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CSecretRoomChange")]
  public partial class S2CSecretRoomChange : global::ProtoBuf.IExtensible
  {
    public S2CSecretRoomChange() {}
    
    private int _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private int _roomState;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomState
    {
      get { return _roomState; }
      set { _roomState = value; }
    }
    private long _closeTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"closeTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long closeTime
    {
      get { return _closeTime; }
      set { _closeTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CSecretStageChange")]
  public partial class S2CSecretStageChange : global::ProtoBuf.IExtensible
  {
    public S2CSecretStageChange() {}
    
    private int _stageId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"stageId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stageId
    {
      get { return _stageId; }
      set { _stageId = value; }
    }
    private int _status;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private SecretMemberInfo _member = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"member", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SecretMemberInfo member
    {
      get { return _member; }
      set { _member = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CSecretBufChange")]
  public partial class S2CSecretBufChange : global::ProtoBuf.IExtensible
  {
    public S2CSecretBufChange() {}
    
    private int _stageId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"stageId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stageId
    {
      get { return _stageId; }
      set { _stageId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _bufId = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"bufId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> bufId
    {
      get { return _bufId; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _bufVal = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"bufVal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> bufVal
    {
      get { return _bufVal; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SecretMemberInfo")]
  public partial class SecretMemberInfo : global::ProtoBuf.IExtensible
  {
    public SecretMemberInfo() {}
    
    private long _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _iconType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"iconType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int iconType
    {
      get { return _iconType; }
      set { _iconType = value; }
    }
    private string _icon;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private int _fightVal;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"fightVal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fightVal
    {
      get { return _fightVal; }
      set { _fightVal = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}