//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: shilian.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SHILIAN")]
  public partial class SHILIAN : global::ProtoBuf.IExtensible
  {
    public SHILIAN() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _name = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _desc = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private int _money = (int)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int money
    {
      get { return _money; }
      set { _money = value; }
    }
    private int _type = (int)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _cycle = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"cycle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string cycle
    {
      get { return _cycle; }
      set { _cycle = value; }
    }
    private string _chess_bg = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"chess_bg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string chess_bg
    {
      get { return _chess_bg; }
      set { _chess_bg = value; }
    }
    private string _chess_small_bg = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"chess_small_bg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string chess_small_bg
    {
      get { return _chess_small_bg; }
      set { _chess_small_bg = value; }
    }
    private string _caption_drop = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"caption_drop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string caption_drop
    {
      get { return _caption_drop; }
      set { _caption_drop = value; }
    }
    private string _boss_drop = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"boss_drop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string boss_drop
    {
      get { return _boss_drop; }
      set { _boss_drop = value; }
    }
    private int _shouci_jiangli = (int)0;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"shouci_jiangli", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int shouci_jiangli
    {
      get { return _shouci_jiangli; }
      set { _shouci_jiangli = value; }
    }
    private string _sweep_drop = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"sweep_drop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sweep_drop
    {
      get { return _sweep_drop; }
      set { _sweep_drop = value; }
    }
    private int _suggest_hero_tips = (int)0;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"suggest_hero_tips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int suggest_hero_tips
    {
      get { return _suggest_hero_tips; }
      set { _suggest_hero_tips = value; }
    }
    private int _open_lv = (int)0;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"open_lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int open_lv
    {
      get { return _open_lv; }
      set { _open_lv = value; }
    }
    private string _icon = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private int _res_id = (int)0;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"res_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int res_id
    {
      get { return _res_id; }
      set { _res_id = value; }
    }
    private string _speed = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private string _clip_copy = "";
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"clip_copy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string clip_copy
    {
      get { return _clip_copy; }
      set { _clip_copy = value; }
    }
    private int _chapter_id = (int)0;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"chapter_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int chapter_id
    {
      get { return _chapter_id; }
      set { _chapter_id = value; }
    }
    private string _chapter_attr = "";
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"chapter_attr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string chapter_attr
    {
      get { return _chapter_attr; }
      set { _chapter_attr = value; }
    }
    private string _chapter_photo = "";
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"chapter_photo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string chapter_photo
    {
      get { return _chapter_photo; }
      set { _chapter_photo = value; }
    }
    private int _chapter_name = (int)0;
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"chapter_name", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int chapter_name
    {
      get { return _chapter_name; }
      set { _chapter_name = value; }
    }
    private int _limit_count = (int)0;
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"limit_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int limit_count
    {
      get { return _limit_count; }
      set { _limit_count = value; }
    }
    private int _hero_limit = (int)0;
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"hero_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int hero_limit
    {
      get { return _hero_limit; }
      set { _hero_limit = value; }
    }
    private string _win_condition = "";
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"win_condition", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string win_condition
    {
      get { return _win_condition; }
      set { _win_condition = value; }
    }
    private string _lose_condition = "";
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"lose_condition", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string lose_condition
    {
      get { return _lose_condition; }
      set { _lose_condition = value; }
    }
    private string _preposition = "";
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"preposition", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string preposition
    {
      get { return _preposition; }
      set { _preposition = value; }
    }
    private int _need_life = (int)0;
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"need_life", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int need_life
    {
      get { return _need_life; }
      set { _need_life = value; }
    }
    private int _common_monster_drop = (int)0;
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"common_monster_drop", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int common_monster_drop
    {
      get { return _common_monster_drop; }
      set { _common_monster_drop = value; }
    }
    private string _scene_config = "";
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"scene_config", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string scene_config
    {
      get { return _scene_config; }
      set { _scene_config = value; }
    }
    private string _monster_config = "";
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"monster_config", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string monster_config
    {
      get { return _monster_config; }
      set { _monster_config = value; }
    }
    private string _goods_show_list = "";
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"goods_show_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string goods_show_list
    {
      get { return _goods_show_list; }
      set { _goods_show_list = value; }
    }
    private string _monster_show_list = "";
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"monster_show_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string monster_show_list
    {
      get { return _monster_show_list; }
      set { _monster_show_list = value; }
    }
    private string _monster_show_boss = "";
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"monster_show_boss", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string monster_show_boss
    {
      get { return _monster_show_boss; }
      set { _monster_show_boss = value; }
    }
    private int _step_limit = (int)0;
    [global::ProtoBuf.ProtoMember(35, IsRequired = false, Name=@"step_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int step_limit
    {
      get { return _step_limit; }
      set { _step_limit = value; }
    }
    private string _fractional_segment = "";
    [global::ProtoBuf.ProtoMember(36, IsRequired = false, Name=@"fractional_segment", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fractional_segment
    {
      get { return _fractional_segment; }
      set { _fractional_segment = value; }
    }
    private int _chess_id = (int)0;
    [global::ProtoBuf.ProtoMember(37, IsRequired = false, Name=@"chess_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int chess_id
    {
      get { return _chess_id; }
      set { _chess_id = value; }
    }
    private int _stage_index = (int)0;
    [global::ProtoBuf.ProtoMember(38, IsRequired = false, Name=@"stage_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int stage_index
    {
      get { return _stage_index; }
      set { _stage_index = value; }
    }
    private int _end = (int)0;
    [global::ProtoBuf.ProtoMember(39, IsRequired = false, Name=@"end", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int end
    {
      get { return _end; }
      set { _end = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SHILIAN_ARRAY")]
  public partial class SHILIAN_ARRAY : global::ProtoBuf.IExtensible
  {
    public SHILIAN_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.SHILIAN> _items = new global::System.Collections.Generic.List<deploy.SHILIAN>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.SHILIAN> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}