//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: shop_oefficient.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SHOP_OEFFICIENT")]
  public partial class SHOP_OEFFICIENT : global::ProtoBuf.IExtensible
  {
    public SHOP_OEFFICIENT() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private float _oefficient = (float)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"oefficient", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float oefficient
    {
      get { return _oefficient; }
      set { _oefficient = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SHOP_OEFFICIENT_ARRAY")]
  public partial class SHOP_OEFFICIENT_ARRAY : global::ProtoBuf.IExtensible
  {
    public SHOP_OEFFICIENT_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.SHOP_OEFFICIENT> _items = new global::System.Collections.Generic.List<deploy.SHOP_OEFFICIENT>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.SHOP_OEFFICIENT> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}