//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ShopMsg.proto
// Note: requires additional types generated from: GuildMsg.proto

using GuildMsg;
namespace ShopMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2STravelShopInfo")]
  public partial class C2STravelShopInfo : global::ProtoBuf.IExtensible
  {
    public C2STravelShopInfo() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CTravelShopInfo")]
  public partial class S2CTravelShopInfo : global::ProtoBuf.IExtensible
  {
    public S2CTravelShopInfo() {}
    
    private readonly global::System.Collections.Generic.List<TravelShop> _shopList = new global::System.Collections.Generic.List<TravelShop>();
    [global::ProtoBuf.ProtoMember(1, Name=@"shopList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TravelShop> shopList
    {
      get { return _shopList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CSecretShopInfo")]
  public partial class S2CSecretShopInfo : global::ProtoBuf.IExtensible
  {
    public S2CSecretShopInfo() {}
    
    private int _shopId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"shopId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int shopId
    {
      get { return _shopId; }
      set { _shopId = value; }
    }
    private readonly global::System.Collections.Generic.List<ShopItem> _itemList = new global::System.Collections.Generic.List<ShopItem>();
    [global::ProtoBuf.ProtoMember(2, Name=@"itemList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ShopItem> itemList
    {
      get { return _itemList; }
    }
  
    private long _closeTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"closeTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long closeTime
    {
      get { return _closeTime; }
      set { _closeTime = value; }
    }
    private bool _isLogin;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"isLogin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isLogin
    {
      get { return _isLogin; }
      set { _isLogin = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SBuyShopItem")]
  public partial class C2SBuyShopItem : global::ProtoBuf.IExtensible
  {
    public C2SBuyShopItem() {}
    
    private int _shopId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"shopId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int shopId
    {
      get { return _shopId; }
      set { _shopId = value; }
    }
    private int _barcode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"barcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int barcode
    {
      get { return _barcode; }
      set { _barcode = value; }
    }
    private int _buyCount;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"buyCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int buyCount
    {
      get { return _buyCount; }
      set { _buyCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CBuyShopItem")]
  public partial class S2CBuyShopItem : global::ProtoBuf.IExtensible
  {
    public S2CBuyShopItem() {}
    
    private int _shopId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"shopId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int shopId
    {
      get { return _shopId; }
      set { _shopId = value; }
    }
    private ShopItem _item;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ShopItem item
    {
      get { return _item; }
      set { _item = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SRefreshShop")]
  public partial class C2SRefreshShop : global::ProtoBuf.IExtensible
  {
    public C2SRefreshShop() {}
    
    private int _shopId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"shopId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int shopId
    {
      get { return _shopId; }
      set { _shopId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CRefreshShop")]
  public partial class S2CRefreshShop : global::ProtoBuf.IExtensible
  {
    public S2CRefreshShop() {}
    
    private TravelShop _shop;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"shop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public TravelShop shop
    {
      get { return _shop; }
      set { _shop = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SQuickBuy")]
  public partial class C2SQuickBuy : global::ProtoBuf.IExtensible
  {
    public C2SQuickBuy() {}
    
    private AttributeType _buyType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"buyType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public AttributeType buyType
    {
      get { return _buyType; }
      set { _buyType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CQuickBuy")]
  public partial class S2CQuickBuy : global::ProtoBuf.IExtensible
  {
    public S2CQuickBuy() {}
    
    private AttributeType _buyType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"buyType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public AttributeType buyType
    {
      get { return _buyType; }
      set { _buyType = value; }
    }
    private int _buyNum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"buyNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int buyNum
    {
      get { return _buyNum; }
      set { _buyNum = value; }
    }
    private int _freeNum = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"freeNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int freeNum
    {
      get { return _freeNum; }
      set { _freeNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TravelShop")]
  public partial class TravelShop : global::ProtoBuf.IExtensible
  {
    public TravelShop() {}
    
    private int _shopId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"shopId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int shopId
    {
      get { return _shopId; }
      set { _shopId = value; }
    }
    private readonly global::System.Collections.Generic.List<ShopItem> _itemList = new global::System.Collections.Generic.List<ShopItem>();
    [global::ProtoBuf.ProtoMember(2, Name=@"itemList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ShopItem> itemList
    {
      get { return _itemList; }
    }
  
    private long _nextTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"nextTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long nextTime
    {
      get { return _nextTime; }
      set { _nextTime = value; }
    }
    private int _refreshCount;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"refreshCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int refreshCount
    {
      get { return _refreshCount; }
      set { _refreshCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShopItem")]
  public partial class ShopItem : global::ProtoBuf.IExtensible
  {
    public ShopItem() {}
    
    private int _barcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"barcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int barcode
    {
      get { return _barcode; }
      set { _barcode = value; }
    }
    private int _state;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}