//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: shouquan_jiangli.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SHOUQUAN_JIANGLI")]
  public partial class SHOUQUAN_JIANGLI : global::ProtoBuf.IExtensible
  {
    public SHOUQUAN_JIANGLI() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _authorization;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"authorization", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string authorization
    {
      get { return _authorization; }
      set { _authorization = value; }
    }
    private int _money = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int money
    {
      get { return _money; }
      set { _money = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SHOUQUAN_JIANGLI_ARRAY")]
  public partial class SHOUQUAN_JIANGLI_ARRAY : global::ProtoBuf.IExtensible
  {
    public SHOUQUAN_JIANGLI_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.SHOUQUAN_JIANGLI> _items = new global::System.Collections.Generic.List<deploy.SHOUQUAN_JIANGLI>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.SHOUQUAN_JIANGLI> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}