//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: skill_spend.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SKILL_SPEND")]
  public partial class SKILL_SPEND : global::ProtoBuf.IExtensible
  {
    public SKILL_SPEND() {}
    
    private int _skill_level;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"skill_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skill_level
    {
      get { return _skill_level; }
      set { _skill_level = value; }
    }
    private int _skill_one;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"skill_one", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skill_one
    {
      get { return _skill_one; }
      set { _skill_one = value; }
    }
    private int _skill_two;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"skill_two", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skill_two
    {
      get { return _skill_two; }
      set { _skill_two = value; }
    }
    private int _skill_three;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"skill_three", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skill_three
    {
      get { return _skill_three; }
      set { _skill_three = value; }
    }
    private int _skill_four;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"skill_four", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skill_four
    {
      get { return _skill_four; }
      set { _skill_four = value; }
    }
    private int _skill_five;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"skill_five", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skill_five
    {
      get { return _skill_five; }
      set { _skill_five = value; }
    }
    private int _skill_six;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"skill_six", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skill_six
    {
      get { return _skill_six; }
      set { _skill_six = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SKILL_SPEND_ARRAY")]
  public partial class SKILL_SPEND_ARRAY : global::ProtoBuf.IExtensible
  {
    public SKILL_SPEND_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.SKILL_SPEND> _items = new global::System.Collections.Generic.List<deploy.SKILL_SPEND>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.SKILL_SPEND> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}