//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: StageFightMsg.proto
// Note: requires additional types generated from: GuildMsg.proto

using GuildMsg;
namespace StageFightMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SStageFightStart")]
  public partial class C2SStageFightStart : global::ProtoBuf.IExtensible
  {
    public C2SStageFightStart() {}
    
    private int _chapterId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"chapterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int chapterId
    {
      get { return _chapterId; }
      set { _chapterId = value; }
    }
    private int _stageId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"stageId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stageId
    {
      get { return _stageId; }
      set { _stageId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _heroIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"heroIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> heroIds
    {
      get { return _heroIds; }
    }
  
    private int _fightVal;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"fightVal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fightVal
    {
      get { return _fightVal; }
      set { _fightVal = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CStageFightStart")]
  public partial class S2CStageFightStart : global::ProtoBuf.IExtensible
  {
    public S2CStageFightStart() {}
    
    private long _fightId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fightId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long fightId
    {
      get { return _fightId; }
      set { _fightId = value; }
    }
    private readonly global::System.Collections.Generic.List<Item> _commonDropItems = new global::System.Collections.Generic.List<Item>();
    [global::ProtoBuf.ProtoMember(2, Name=@"commonDropItems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Item> commonDropItems
    {
      get { return _commonDropItems; }
    }
  
    private readonly global::System.Collections.Generic.List<Item> _captionDropItems = new global::System.Collections.Generic.List<Item>();
    [global::ProtoBuf.ProtoMember(3, Name=@"captionDropItems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Item> captionDropItems
    {
      get { return _captionDropItems; }
    }
  
    private readonly global::System.Collections.Generic.List<Item> _bossDropItems = new global::System.Collections.Generic.List<Item>();
    [global::ProtoBuf.ProtoMember(4, Name=@"bossDropItems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Item> bossDropItems
    {
      get { return _bossDropItems; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SStageFightEnd")]
  public partial class C2SStageFightEnd : global::ProtoBuf.IExtensible
  {
    public C2SStageFightEnd() {}
    
    private long _fightId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fightId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long fightId
    {
      get { return _fightId; }
      set { _fightId = value; }
    }
    private FightResultParam _resultParam;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"resultParam", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public FightResultParam resultParam
    {
      get { return _resultParam; }
      set { _resultParam = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CStageFightEnd")]
  public partial class S2CStageFightEnd : global::ProtoBuf.IExtensible
  {
    public S2CStageFightEnd() {}
    
    private long _fightId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fightId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long fightId
    {
      get { return _fightId; }
      set { _fightId = value; }
    }
    private FightResultType _result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public FightResultType result
    {
      get { return _result; }
      set { _result = value; }
    }
    private StageInfo _stageInfo = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"stageInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public StageInfo stageInfo
    {
      get { return _stageInfo; }
      set { _stageInfo = value; }
    }
    private DropReward _reward = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DropReward reward
    {
      get { return _reward; }
      set { _reward = value; }
    }
    private readonly global::System.Collections.Generic.List<HeroExp> _heroExp = new global::System.Collections.Generic.List<HeroExp>();
    [global::ProtoBuf.ProtoMember(5, Name=@"heroExp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<HeroExp> heroExp
    {
      get { return _heroExp; }
    }
  
    private int _difficulty;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"difficulty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int difficulty
    {
      get { return _difficulty; }
      set { _difficulty = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SStageFightMopup")]
  public partial class C2SStageFightMopup : global::ProtoBuf.IExtensible
  {
    public C2SStageFightMopup() {}
    
    private int _chapterId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"chapterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int chapterId
    {
      get { return _chapterId; }
      set { _chapterId = value; }
    }
    private int _stageId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"stageId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stageId
    {
      get { return _stageId; }
      set { _stageId = value; }
    }
    private int _count;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CStageFightMopup")]
  public partial class S2CStageFightMopup : global::ProtoBuf.IExtensible
  {
    public S2CStageFightMopup() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<MopupResult> _mopup = new global::System.Collections.Generic.List<MopupResult>();
    [global::ProtoBuf.ProtoMember(2, Name=@"mopup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MopupResult> mopup
    {
      get { return _mopup; }
    }
  
    private int _count = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MopupResult")]
  public partial class MopupResult : global::ProtoBuf.IExtensible
  {
    public MopupResult() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _gold = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private int _exp = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private readonly global::System.Collections.Generic.List<Item> _item = new global::System.Collections.Generic.List<Item>();
    [global::ProtoBuf.ProtoMember(4, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Item> item
    {
      get { return _item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SStageRest")]
  public partial class C2SStageRest : global::ProtoBuf.IExtensible
  {
    public C2SStageRest() {}
    
    private int _stageId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"stageId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stageId
    {
      get { return _stageId; }
      set { _stageId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CStageRest")]
  public partial class S2CStageRest : global::ProtoBuf.IExtensible
  {
    public S2CStageRest() {}
    
    private int _stageId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"stageId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stageId
    {
      get { return _stageId; }
      set { _stageId = value; }
    }
    private int _chapterId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"chapterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int chapterId
    {
      get { return _chapterId; }
      set { _chapterId = value; }
    }
    private int _resetCount;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"resetCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int resetCount
    {
      get { return _resetCount; }
      set { _resetCount = value; }
    }
    private int _battleNum;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"battleNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int battleNum
    {
      get { return _battleNum; }
      set { _battleNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SStageOpenChest")]
  public partial class C2SStageOpenChest : global::ProtoBuf.IExtensible
  {
    public C2SStageOpenChest() {}
    
    private int _chapterId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"chapterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int chapterId
    {
      get { return _chapterId; }
      set { _chapterId = value; }
    }
    private int _chestIndex;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"chestIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int chestIndex
    {
      get { return _chestIndex; }
      set { _chestIndex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SStageJumpDialogue")]
  public partial class C2SStageJumpDialogue : global::ProtoBuf.IExtensible
  {
    public C2SStageJumpDialogue() {}
    
    private int _chapterId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"chapterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int chapterId
    {
      get { return _chapterId; }
      set { _chapterId = value; }
    }
    private int _stageId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"stageId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stageId
    {
      get { return _stageId; }
      set { _stageId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SPvPSearchEnemy")]
  public partial class C2SPvPSearchEnemy : global::ProtoBuf.IExtensible
  {
    public C2SPvPSearchEnemy() {}
    
    private int _cityId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cityId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cityId
    {
      get { return _cityId; }
      set { _cityId = value; }
    }
    private int _fightVal;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"fightVal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fightVal
    {
      get { return _fightVal; }
      set { _fightVal = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CPvPSearchEnemy")]
  public partial class S2CPvPSearchEnemy : global::ProtoBuf.IExtensible
  {
    public S2CPvPSearchEnemy() {}
    
    private int _cityId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cityId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cityId
    {
      get { return _cityId; }
      set { _cityId = value; }
    }
    private readonly global::System.Collections.Generic.List<HeroInfo> _heroList = new global::System.Collections.Generic.List<HeroInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"heroList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<HeroInfo> heroList
    {
      get { return _heroList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SMortgageKitty")]
  public partial class C2SMortgageKitty : global::ProtoBuf.IExtensible
  {
    public C2SMortgageKitty() {}
    
    private int _chapterId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"chapterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int chapterId
    {
      get { return _chapterId; }
      set { _chapterId = value; }
    }
    private int _stageId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"stageId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stageId
    {
      get { return _stageId; }
      set { _stageId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroExp")]
  public partial class HeroExp : global::ProtoBuf.IExtensible
  {
    public HeroExp() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _addExp = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"addExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int addExp
    {
      get { return _addExp; }
      set { _addExp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}