//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: task_point_exchange.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TASK_POINT_EXCHANGE")]
  public partial class TASK_POINT_EXCHANGE : global::ProtoBuf.IExtensible
  {
    public TASK_POINT_EXCHANGE() {}
    
    private uint _task_point;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"task_point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint task_point
    {
      get { return _task_point; }
      set { _task_point = value; }
    }
    private readonly global::System.Collections.Generic.List<deploy.TASK_POINT_EXCHANGE.item> _ItemTable = new global::System.Collections.Generic.List<deploy.TASK_POINT_EXCHANGE.item>();
    [global::ProtoBuf.ProtoMember(2, Name=@"ItemTable", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.TASK_POINT_EXCHANGE.item> ItemTable
    {
      get { return _ItemTable; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"item")]
  public partial class item : global::ProtoBuf.IExtensible
  {
    public item() {}
    
    private uint _item_id = (uint)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }
    private int _amount = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int amount
    {
      get { return _amount; }
      set { _amount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TASK_POINT_EXCHANGE_ARRAY")]
  public partial class TASK_POINT_EXCHANGE_ARRAY : global::ProtoBuf.IExtensible
  {
    public TASK_POINT_EXCHANGE_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.TASK_POINT_EXCHANGE> _items = new global::System.Collections.Generic.List<deploy.TASK_POINT_EXCHANGE>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.TASK_POINT_EXCHANGE> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}