//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: task_data.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TASK_DATA")]
  public partial class TASK_DATA : global::ProtoBuf.IExtensible
  {
    public TASK_DATA() {}
    
    private uint _task_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"task_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint task_id
    {
      get { return _task_id; }
      set { _task_id = value; }
    }
    private int _task_name = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"task_name", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int task_name
    {
      get { return _task_name; }
      set { _task_name = value; }
    }
    private int _task_type = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"task_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int task_type
    {
      get { return _task_type; }
      set { _task_type = value; }
    }
    private string _icon = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private int _task_desc = (int)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"task_desc", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int task_desc
    {
      get { return _task_desc; }
      set { _task_desc = value; }
    }
    private uint _pre_task_id = (uint)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"pre_task_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint pre_task_id
    {
      get { return _pre_task_id; }
      set { _pre_task_id = value; }
    }
    private int _role_level = (int)0;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"role_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int role_level
    {
      get { return _role_level; }
      set { _role_level = value; }
    }
    private uint _condition_type = (uint)0;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"condition_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint condition_type
    {
      get { return _condition_type; }
      set { _condition_type = value; }
    }
    private int _param1 = (int)0;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"param1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int param1
    {
      get { return _param1; }
      set { _param1 = value; }
    }
    private int _param2 = (int)0;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"param2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int param2
    {
      get { return _param2; }
      set { _param2 = value; }
    }
    private int _jump_ui_sys = (int)0;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"jump_ui_sys", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int jump_ui_sys
    {
      get { return _jump_ui_sys; }
      set { _jump_ui_sys = value; }
    }
    private string _jump_ui = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"jump_ui", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jump_ui
    {
      get { return _jump_ui; }
      set { _jump_ui = value; }
    }
    private int _off_now = (int)0;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"off_now", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int off_now
    {
      get { return _off_now; }
      set { _off_now = value; }
    }
    private readonly global::System.Collections.Generic.List<deploy.TASK_DATA.Item> _ItemTable = new global::System.Collections.Generic.List<deploy.TASK_DATA.Item>();
    [global::ProtoBuf.ProtoMember(14, Name=@"ItemTable", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.TASK_DATA.Item> ItemTable
    {
      get { return _ItemTable; }
    }
  
    private int _role_exp = (int)0;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"role_exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int role_exp
    {
      get { return _role_exp; }
      set { _role_exp = value; }
    }
    private int _money = (int)0;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int money
    {
      get { return _money; }
      set { _money = value; }
    }
    private int _diamond = (int)0;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private int _energy = (int)0;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"energy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int energy
    {
      get { return _energy; }
      set { _energy = value; }
    }
    private int _task_point = (int)0;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"task_point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int task_point
    {
      get { return _task_point; }
      set { _task_point = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Item")]
  public partial class Item : global::ProtoBuf.IExtensible
  {
    public Item() {}
    
    private uint _item_id = (uint)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }
    private int _amount = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int amount
    {
      get { return _amount; }
      set { _amount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TASK_DATA_ARRAY")]
  public partial class TASK_DATA_ARRAY : global::ProtoBuf.IExtensible
  {
    public TASK_DATA_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.TASK_DATA> _items = new global::System.Collections.Generic.List<deploy.TASK_DATA>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.TASK_DATA> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}