//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: TestMsg.proto
namespace TestMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2STestMsg")]
  public partial class C2STestMsg : global::ProtoBuf.IExtensible
  {
    public C2STestMsg() {}
    
    private int _cmdCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cmdCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cmdCode
    {
      get { return _cmdCode; }
      set { _cmdCode = value; }
    }
    private string _resultInfo = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"resultInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string resultInfo
    {
      get { return _resultInfo; }
      set { _resultInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CTestMeg")]
  public partial class S2CTestMeg : global::ProtoBuf.IExtensible
  {
    public S2CTestMeg() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private string _resultInfo = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"resultInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string resultInfo
    {
      get { return _resultInfo; }
      set { _resultInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}