//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: xunluo_type.proto
namespace deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XUNLUO_TYPE")]
  public partial class XUNLUO_TYPE : global::ProtoBuf.IExtensible
  {
    public XUNLUO_TYPE() {}
    
    private int _type_ID = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int type_ID
    {
      get { return _type_ID; }
      set { _type_ID = value; }
    }
    private string _task_type = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"task_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string task_type
    {
      get { return _task_type; }
      set { _task_type = value; }
    }
    private string _task_desc = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"task_desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string task_desc
    {
      get { return _task_desc; }
      set { _task_desc = value; }
    }
    private string _icon = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XUNLUO_TYPE_ARRAY")]
  public partial class XUNLUO_TYPE_ARRAY : global::ProtoBuf.IExtensible
  {
    public XUNLUO_TYPE_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<deploy.XUNLUO_TYPE> _items = new global::System.Collections.Generic.List<deploy.XUNLUO_TYPE>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<deploy.XUNLUO_TYPE> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}